### ISSUE TITLE
Make a stable CSV output

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/dballe#1]
Issue reported by Massimo Bider.

The output of `dbamsg dump --csv` is changed in 7.2:

- Some field names are changed (e.g. `edition` is now `master_table_number`)
- The fields are now quoted with `""`
- The date has now a uncomfortable format
   - e.g. `"representative_time","2015-5-27 9:0:0"` was `date,2015-05-27 09:00:00`

**Comment by spanezz** [comment]
I fixed the date and removed the quoting on integer, decimal and missing fields.

I left the new names following a rename effort in wreport with the goal of using names that actually match how things are named in the BUFR and CREX standards: for that reason I would rather keep the new names. If that causes problems, I am available to discuss possible solutions.

**Comment by spanezz** [comment]
Branch merged into devel, closing bug.
