### ISSUE TITLE
[centos] Sqlite3 does not recognize token "0xFFFFFFFE"

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/dballe#101]
Hex literals were introduced in [`sqlite3-3.8.6`](http://sqlite.org/lang_expr.html#hexint).
```
db_sql_sqlite.query_unsigned:[N6dballe3sql12error_sqliteE] executing INSERT INTO dballe_test VALUES (0xFFFFFFFE):unrecognized token: "0xFFFFFFFE"
```

**Comment by brancomat** [comment]
Ci sono stati altri problemi con sqlite (tipo: https://github.com/ARPA-SIMC/libsim/issues/37) che ci hanno di fatto portato a fare un cherry-pick delle versioni di sqlite  (vedi anche thread mail " "Re: problemi libsim su radicchio (fedora 24) - AGGIORNAMENTO")

La mia proposta è di ricompilare per CentOs una delle versioni sqlite attualmente stable per noi:
 - 3.19.1 (che attualmente usiamo su f24, backporting fatto da noi)
 - 3.8.10 (attualmente su f20, ultima versione disponibile sui repo di sistema)

In realtà più per standardizzare i comportamenti attesi che per il bug in questione che si potrebbe chiudere in N altri modi.
Cambio gli assignees che @pat1 e @dcesari sono i più interessati a centos al momento

**Comment by edigiacomo** [comment]
In 36411a9 ho modificato il test in modo che si comportino diversamente se viene usata una versione di sqlite3 < 3.8.6. In questo modo, non ho toccato il test originale e il test su centos ha esito positivo.

Se invece preferite supportare solo versioni >= 3.19.1, allora forse sarebbe meglio modificare il configure.ac in modo che esploda se si trova un versione di sqlite3 non sufficientemente aggiornata.

Lascio quindi l'onore a @pat1 e @dcesari di scegliere se fare il merge della suddetta commit (branch `issue101`) oppure aprire una issue per evitare l'uso di dballe con sqlite3 < 3.19.1 (potete assegnarla a me) oppure altro.

**Comment by dcesari** [comment]
Siccome la versione su CentOS è tra quelle pre-"problemi su radicchio" sqlite-3.7.17-8.el7, preferirei non dover compilare una versione apposta di sqlite per CentOS se si può evitarlo. Porto progressivamente la mano sul pulsante "Create pull request" nell'attesa di eventuali obiezioni.

**Comment by brancomat** [comment]
> preferirei non dover compilare una versione apposta di sqlite per CentOS se si può evitarlo

Ho appena parlato con @pat1, ve la giocate a birra e salsicce, lui se capisco bene sarebbe più per usare una versione di sqlite di cui siamo certi di funzionamento e performance, in quel caso però ha ragione @edigiacomo e andrebbe decisa una versione minima di riferimento gestita dal configure.

Viste le tempistiche bibliche di elaborazione di questi problemi preferirei lasciare le cose in uno stato meno sospeso, procedo unilateralmente a mergiare la #102 e intanto licenziamo quella, chiudo la issue poi se emergono bug o problemi di performance o voglia di fare benchmark ne riparliamo.

**Comment by dcesari** [comment]
Ai tempi di sqlite versione 3.7 ~ 3.8 eravamo **CERTI** della sua stabilità di funzionamento e delle sue performance, mi sembra masochista forzare in CentOS 7 una versione più nuova perché successivamente c'è stato un temporaneo oscuramento di sqlite, considerato anche che da sqlite dipendono altri mille pacchetti di CentOS e che difficilmente su CentOS 7 avanzeranno ad una versione di sqlite del periodo oscuro.
