### ISSUE TITLE
Possible optimizations in dballe access from fortran/libsim

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/dballe#117]
We can collect here some typical use cases of dballe access from fortran and corresponding optimization strategies, e.g. retrieving all the attributes as in #114 .
Attached is the trace of a libsim read and write of BUFR file when no filtering options are given.
[trace.zip](https://github.com/ARPA-SIMC/dballe/files/2102371/trace.zip)

**Comment by edigiacomo** [comment]
The prototype `dballe-7.33-3` is installed in `ventiquattro.metarpa`.

**Comment by spanezz** [comment]
If I understood correctly, in this case it should not be a hint given in the URI, but a query parameter, like when setting `enqc('query', 'best')`.

Yes, please open a separate issue for that.

**Comment by dcesari** [comment]
I send an email since some complex issues arose.

**Comment by dcesari** [comment]
After last commit the results are correct. I managed to set up a more challenging test which does only [query with the f03 API](https://github.com/ARPA-SIMC/libsim/blob/master/examples/example_dballe_read_vector.F03), without storing in a vol7d, so I could test with a big SYNOP file. Now `query=attrs` really gives an improvement:

```
# without attrs (similar for previous dballe version)
real	0m29.839s
user	0m20.884s
sys	0m8.776s
# with attrs
real	0m25.842s
user	0m17.343s
sys	0m8.324s
```

So it's worth to keep this feature, thanks! I'll open an issue on libsim to decide the strategy for activating this query parameter.

**Comment by spanezz** [comment]
Ok, thanks! It looks like a 6% improvement in user time, which isn't bad at all, though I was hoping for much more. I'll merge the changes to master, though
