### ISSUE TITLE
dballe python api: 'dballe.Record' object has no attribute 'set_station_context'

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#118]
starting from dballe -7.33-2 :

Exception Type: AttributeError at /borinud/api/v1/geojson/-/*/*/*/*/*/stations
Exception Value: 'dballe.Record' object has no attribute 'set_station_context'

with code like this:
rec.set_station_context()

**Comment by spanezz** [comment]
Just delete taht line: set_station_context did nothing, and had been deprecated for a long time.

The python API makes the distinction between station data and measured data at query or insert time.
