### ISSUE TITLE
Modulo python dballe.volnd

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#119]
Lo sta usando qualcuno il modulo python dballe.volnd?

**Comment by dcesari** [comment]
A me non risulta, grazie.

**Comment by amontani** [comment]
Anche a me non risulta. Ciao.

**Comment by brancomat** [comment]
Anche per me è no. Per sicurezza ho greppato i sorgenti delle proc operative e di meteomixer e anche lì nessun risultato.

**Comment by pat1** [comment]
volnd è usata raramente, ma usata; ad esempio del codice della modelliststica marina.

**Comment by pat1** [comment]
Può valer la pena riprogettare volnd e di conseguenza l'export verso R per seguire il modello dati di vol7d, per avere un'API uniforme per l'export da DB-All.e verso volumi

**Comment by dcesari** [comment]
Non ho mai provato volnd, però alla lunga l'approccio del volume megalitico tipo vol7d a me è risultata un mezzo fallimento dal punto di vista della facilità di programmazione, propongo di discutere se vale davvero la pena investire.

**Comment by spanezz** [comment]
Ok, se volnd è usato allora non lo tolgo. Se per qualche motivo smette di essere usato, allora fatemelo sapere che tolgo una cosa complessa da mantenere.

Se si desidera invece riprogettarlo sul serio, apriamo un ticket apposta
