### ISSUE TITLE
Ottimizzazione estrazioni per vol7d

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#121]
Facendo un po' di benchmark con DB-All.e, sembra che il 33% del tempo di una query a SQLite lato DB-All.e sia speso copiando i dati in una strutura a record che possa essere querata via Fortran tramite le varie enqi/enqc/enqd.

Immagino che vol7d legga i dati di contesto (lat, lon, datetime, level, timerange, ...) da DB-All.e per poi copiarli in matrici che sono piú o meno sempre quelle. Se è cosí, possiamo valutare l'aggiunta di una API Fortran per riempire matrici vol7d, che salti questo passaggio?

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
