### ISSUE TITLE
Serialization/deserialization and merge of db::Summary

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#122]
@edigiacomo needs to be able to:

- [x] serialize db::Summary objects to JSON
- [x] deserialize db::Summary objects from JSON
- [x] merge the contents of db::Summary objects
- [x] generate a db::Summary object from a stream of BUFR

**Comment by spanezz** [comment]
Partial results are in branch issue122

**Comment by spanezz** [comment]
At the C++ library level, all functionality you requested is implemented. @edigiacomo how would you like it accessible? Is C++ enough? You prefer from python? From the command line?

**Comment by edigiacomo** [comment]
Thanks Enrico! Querying the summary from Python would be very useful. @pat1 @dcesari @brancomat what do you think about the cli interface?

**Comment by pat1** [comment]
non sono sicuro di aver capito la domanda e quindi nemmeno della risposta. Credo sia utile in python, ma di una cli al momento non saprei cosa farmene.

**Comment by brancomat** [comment]
al momento non ho esigenze in merito, anche a me l'interfaccia python pare sufficiente
(anche se in genere quando scrivo di queste cose me ne pento qualche mese dopo)

**Comment by edigiacomo** [comment]
Siamo arrivati alla conclusione che le API C++ e Python sono sufficienti. La CLI ci servirebbe al momento solo per generare il summary dal BUFR e fare il merge con altri summary ma direi che per ora possiamo fare noi uno script in Python (al massimo ne riparliamo se le necessità si ampliano).

Se parte Python è già pronta, possiamo provarla non appena ci dai due dritte sull'utilizzo.

Grazie!

**Comment by spanezz** [comment]
Most of the API (C++ and Python) is ready, I just need to export to python the API about adding messsage contents to the summary.

Do you want to add ALL message contents to a summary (including, say, station name and equipment information), or only some information (like the variables measured, defined in some way to be defined)?

**Comment by spanezz** [comment]
This is now implemented in the `issue122` branch, that is pending merge into master for a go-ahead on the Fortran side.

**Comment by spanezz** [comment]
Closing since 8.0 is now in master.
