### ISSUE TITLE
Unrecognized query strings in db URI

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/dballe#123]
As indirectly noted in #117 , optional query strings (hints or any other) appended to the db uri, at least for sqlite, if not recognized become part of the filename i.e. `sqlite:/path/to/dballe.sqlite?a=b` tries to access a file named exactly `/path/to/dballe.sqlite?a=b`.

From my point of view an unrecognized optional string should be ignored to avoid incompatibilities among libsim/dballe versions if e.g. we hardcode some options in libsim calls to dballe since libsim version x.y.z; so the previous example should point undoubtfully to `/path/to/dballe.sqlite`.

**Comment by spanezz** [comment]
Note that SQLite is going to support URL query strings by default soon: https://sqlite.org/c3ref/open.html

At the moment I'm just stripping the query string away, in some future it might be convenient instead to just enable URL parsing in sqlite, after making sure that all the platforms we support can handle that.

A good test is seeing if `sqlite3 file:foo.sqlite?a=b 'CREATE TABLE test (col INT)'` creates a file called `foo.sqlite` or `foo.sqlite?a=b` in each platform.
