### ISSUE TITLE
dbadb import fail on mysql

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#124]
with mariadb-5.5.43-1.fc20.i686 dbadb import fail with:

cannot execute 'START TRANSACTION READ WRITE':You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'READ WRITE' at line 1

**Comment by spanezz** [comment]
In https://dev.mysql.com/doc/refman/5.7/en/commit.html "START TRANSACTION READ WRITE" is a valid statement. Which distribution has mariadb 5.5?

I cannot find any documentation for that version of mariadb. Could you find and post me the equivalent documentation page, possibly from the MariaDB documentation package of the distribution that you use, so I can check what *is* supported and see if there's a backwards compatible way to start a transaction?

**Comment by spanezz** [comment]
Fedora 20 should really be discontinued. Why devel blocking? Is development still being made on Fedora 20?

**Comment by pat1** [comment]
programmata migrazione a centos 7 tra un mese.
