### ISSUE TITLE
C++ API (use cases)

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/dballe#128]
* Conversion to BUFR (`meteo-vm2`, `erg5`):
    * Create datetime, level, timerange and var
    * Create a message
    * Add data and station data to the message 
    * Create a list of messages
    * Export messages to BUFR
* Parse a BUFR file (`meteo-vm2`):
    * Iterate over messages in a file
    * Read data and station data from a message

**Comment by spanezz** [comment]
In branch `issue128`, I added to the stable API:
```
dballe/importer.h
dballe/exporter.h
Message.get_type()
Message.get_shortcut()
Message.foreach_var()
```
arkimet (branch `dballe`) now can build and work using only the stable DB-All.e API.

**Comment by edigiacomo** [comment]
Thank you!

Two observations:

1. I cannot find `Message.get_shortcut()` in the source code.
2. It could be useful to separate the header of the public API (`nobase_dist_dballeinclude_HEADERS`) from the internal headers (`noinst_HEADERS`).

**Comment by spanezz** [comment]
Whoops, I missed a push. Now get_shortcut() should be there: https://github.com/ARPA-SIMC/dballe/blob/issue128/dballe/message.h#L55

**Comment by spanezz** [comment]
I like the idea of not distributing the headers for the non-stable API, but they are still needed at least to build the Qt version of provami.

**Comment by spanezz** [comment]
Now branch `issue128` has `Message::set`, in 3 versions

**Comment by spanezz** [comment]
I want to sleep over this, have a look again at the API tomorrow, and if I still like it, we can call this a release.

**Comment by spanezz** [comment]
I did some other fine tuning, and we can call this a release.

**Comment by spanezz** [comment]
Assigning to @edigiacomo for validating if the API is enough to build the software he is maintaining

**Comment by spanezz** [comment]
Closing after release of 8.0
