### ISSUE TITLE
Is AOF support still used?

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#129]
Hello.

There is still code in DB-All.e to read and write messages in AOF format. Are they still used, or can I remove it?

**Comment by dcesari** [comment]
We can dismiss it, if requires extra manpower for maintenance.

**Comment by spanezz** [comment]
Thank you. I removed it in `issue128`, not yet merged in master

**Comment by spanezz** [comment]
issue128 is now merged into mastaer
