### ISSUE TITLE
query con lonmin=0, lonmax=360

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#132]
Usando il buon senso, se faccio una query con `lonmin=x`, `lonmax=x+360.0`, l'intenzione sarebbe di querare tutto il dominio, in modo equivalente a non settare `lonmin` e `lonmax`, e al momento è cosí.

Sto facendo delle modifiche all'interno della gestione dei record di query, e mi farebbe comodo salvare questi range usando cose piú furbe. Però, essendo furbe, sanno che le longitudini sono su un angolo giro, e normalizzano `x+360` a `x`. Di conseguenza, settare `lonmin=x`, `lonmax=x+360` sarebbe come settare `lonmin=lonmax=x`, e cioè come settare `lon=x`, che quindi fa match su una specifica longitudine invece che su ogni longitudine.

Sarebbe un problema per voi se DB-All.e normalizzasse tutte le longitudini a `(-180, 180)` in fase di input?

Avete codice che dipende dal fatto che querare `(0, 360)` o `(x, x+360)` sia equivalente a fare unset di `lon`?

**Comment by edigiacomo** [comment]
Io non proprio codice che fa query geografiche direttamente su un dbadb, per fortuna :)

**Comment by spanezz** [comment]
Nota: se serve posso aggiungere all'API fortran una chiamata `idba_setlatlon(lat, lon)` in grado di gestire il caso `(x, x+360)`: avendo entrambi i dati assieme, posso vedere ceh se i valori sono diversi in entrata e uguali dopo la normalizzazione, era stato richiesto un intervallo di 360°

**Comment by dcesari** [comment]
> Sarebbe un problema per voi se DB-All.e normalizzasse tutte le longitudini a (-180, 180) in fase di input?
Se non abbiamo applicazioni in Alaska o in Chukotka, che sono a cavallo del meridiano 180, credo che difficilmente sarebbe un problema.
Una soluzione globale al problema delle longitudini periodiche non è comunque banale, anche openstreetmap ne soffre:
https://www.openstreetmap.org/#map=7/71.133/-179.780

**Comment by spanezz** [comment]
No, è solo in fase di query: in fase di input, tutto viene normalizzato tra -180 e 180, e le query funzionano bene a cavallo del meridiano 180.

L'unica differenza è passare dalla situazione in cui, in fase di query, `(0, 360)` significa "qualunque longitudine", alla situazione in cui `(0, 360)' viene normalizzato a `(0, 0)` e significa "solo il merdiano di Greenwich`.

Da un confronto telefonico sembra che questo, per il mondo Fortran, al momento non sia un problema.

**Comment by pat1** [comment]
io non ho nessuna query con (0, 360) o almeno credo.
