### ISSUE TITLE
comportamento voglioquesto dopo idba_messaggi

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#133]
Ho notato che al momento, fare una `voglioquesto` dopo una `idba_messaggi` restituisce tutte le variabili, siano esse di stazione o con livello/scadenza/datetime, a prescindere dalla `setcontextana`.

Con la riorganizzazione che sto facendo, c'è la possibilità di allineare il comportamento a quello nel caso del database, con la voglioquesto che restituisce le variabili stazione o quelle misurate a seconda della setcontextana. Sembrerebbe desiderabile, ma anche un cambiamento di comportamento.

Domanda 1: cosa sarebbe preferibile?

Domanda 2: la api `idba_messaggi` è usata? Se alla fine non è usata, l'altra possibilità sarebbe rimuoverla.

**Comment by pat1** [comment]
per quanto riguarda il punto 2 nella libsim:
```
grep idba_messaggi *.F03
dballe_class_attrappend.F03:    ier =  idba_messaggi(dbasession_init%sehandle,filename, lmode, lformat)
dballe_class_attrappend.F03:  ier = idba_messaggi(session%sehandle,session%filename,session%mode,session%format)
dballe_class.F03:    ier =  idba_messaggi(dbasession_init%sehandle,filename, lmode, lformat)
dballe_class.F03:  ier = idba_messaggi(session%sehandle,session%filename,session%mode,session%format)
```

per quanto riguarda il punto 1 la risposta non è facile: è possibile che io abbia ovviato con filtri appositi all'attuale comportamento, ma bisogna ripercorrere parecchie centinaia di linee di codice per ipotizzarne l'uso.
Direi che una risposta più sensata sarebbe quella di utilizzare gli appositi test della libsim.

**Comment by pat1** [comment]
è molto probabile che i dati su file vengano sempre importati in un memdb per ovviare ai problemi proprio in oggetto di questa issue; ho necessità di tempo per indagare e per mie assenze la cosa potrò farla in dicembre

**Comment by spanezz** [comment]
Closing after 8.0 release
