### ISSUE TITLE
New names for Fortran API functions

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#138]
A lot of time has passed since the Fortran API was first specified, and I feel like the current function names reflect another scope and another era compared to what DB-All.e is today.

I would like to specify an alternative set of names, in English, and self-descriptive, add them to the API, and keep the current ones as aliases in order not to break the old code.

I'm opening this issue to track the idea, we could draft the function names either here, or in a meeting.

**Comment by pat1** [comment]
la mia opinione è che solo le "nuove api" in fortran 2003 dovrebbero essere utilizzate nella maggioranza dei casi. Queste API sono messe a disposizione dalla libsim. Le api fortran 77/90 rimangono ovviamente a disposizione maggiormente come "low level API".
In questa situazione qualsiasi restiling delle API a mio parere non ha importanza e qualsiasi risorsa necessaria può essere utilizzata su altri task a più alta priorità.  Ad esempio a stabilizzare o ottimizzare le API fortran 2003

**Comment by spanezz** [comment]
I tracked the issue to here:
https://github.com/ARPA-SIMC/arkimet/blob/master/arki/runtime/arki-scan.cc#L50

The return value of dispatch is ignored, and foreach_source will return true if nothing raised an exception. This means that if everything was successfully not imported (dispatched in error dataset, copied to copyko files and so on), then arki-scan returns true.

I already have a draft fix. The question is what is the desired behaviour. I assume I should return error in case at least one data ended up in the error dataset.

What if all data imported correctly except one that was a duplicate?

**Comment by spanezz** [comment]
I pushed a fix: 9ebd91ececc2c9100313efc8f281bd34ed66c3ba

**Comment by spanezz** [comment]
The new API names are now available in DB-All.e 8.0.

Documentation now refers to the new API names, and documents the old ones as deprecated compatibility aliases.

I have no plan of removing support for the old names for the time being.
