### ISSUE TITLE
bufr con carattere binario in LONG STATION OR SITE NAME

### ISSUE THREAD

**Issue by amontani** [ARPA-SIMC/dballe#139]
stiamo estraendo i dati da pluvio_dpcn, utilizzando una script che avevi dati a Maria Stefania.
Il dpcn.conf e` questo:
[pluvio_dpcn]
bounding = POLYGON ((15.0943699999999996 36.6805700000000030, 11.9543999999999997 36.7914299999999983, 0.0000000000000000 41.9450000000000003, 6.8425000000000002 45.7663900000000012, 7.0277799999999999 45.8674999999999997, 7.0650000000000004 45.8838900000000010, 8.3661100000000008 46.4375000000000000, 11.3658300000000008 46.9358300000000028, 12.0819399999999995 46.9427799999999991, 13.6869399999999999 46.4961100000000016, 18.4761699999999998 40.1198300000000003, 18.3475000000000001 39.8079999999999998, 15.0943699999999996 36.6805700000000030))
description = Precipitazioni orarie nazionali da DPCN
filter = product: BUFR:t=pluvio_dpcn
format = bufr
index = reftime, product, area
name = pluvio_dpcn
path = http://arkioss.metarpa:8090/dataset/pluvio_dpcn
replace = yes
restrict = simc
server = http://arkioss.metarpa:8090
step = daily
type = remote
unique = reftime, product, area

Il dpcn.query   e`:
reftime:>=2018-10-17 00:00,<=2018-10-18 00:00;

La script va benissimo, ma nel bufr che viene generato, compaiono alcuni caratteri strani nel nome della stazione.
Ecco qui sotto un esempio

001019 LONG STATION OR SITE NAME(CCITTIA5): Rocca San Giovanni, C.da Vallev<C3>

Questo fa "incartare" un dbadb import successivo.
Si puo` modificare  in qualche modo l'estrazione in modo che il campo con il nome della stazione sia vuoto.
Lavorando alla verifica del modello, questo campo non serve, visto che utilizziamo solo lat/lon e altezza del punto stazione. Che ne dici?

**Comment by amontani** [comment]
[my_bufr_AM.zip](https://github.com/ARPA-SIMC/dballe/files/2657209/my_bufr_AM.zip)
ecco il bufr incriminato, se occorre.
Grazie e ciao.

**Comment by edigiacomo** [comment]
Proseguo la conversazione privatamente su mail con @amontani. Se per caso è un bug di dballe riapro una issue su github.

**Comment by edigiacomo** [comment]
The string `Rocca San Giovanni, C.da Vallevò` is 32 characters but 33 bytes. I suppose that dballe truncates the string at the 32nd byte and then Postgres complains about a malformed multibyte character:

```
ERROR cannot escape string 'Rocca San Giovanni, C.da Vallev�': incomplete multibyte character
```

This snippet shows what I'm trying to say

```
#include <dballe/var.h>
#include <iostream>
#include <cstring>

int main()
{
    const char* s = "Rocca San Giovanni, C.da Vallevò";
    auto var = dballe::var(WR_VAR(0, 1, 19), s);
    std::cout << "String length: " << strlen(s) << std::endl;
    std::cout << "Var value: " << var.enqc() << std::endl;
    std::cout << "Var string length:" << strlen(var.enqc()) << std::endl;
    return 0;
}
```

```
String length: 33
Var value: Rocca San Giovanni, C.da Vallev
Var string length:32
```

I dont' know if wreport/dballe should truncate the string at optimal place or raise an error. Maybe it should be responsibility of the user to feed a valid string or decide whether raise an error or truncate it properly.

**Comment by dcesari** [comment]
Well, if station names are normally truncated to 32 bytes, I think wreport/dballe should instead silently truncate the string at optimal place, being it 31, 30 or whatever, without any hint from the user, 32 is not a Sacred Cow.

**Comment by edigiacomo** [comment]
I'm not an encoding expert (as in "I don't know what I'm talking about"), but maybe dballe would need to know the encoding (e.g. utf-8, iso-8859-1, utf-16, etc) of the string to truncate it at optimal place?

**Comment by edigiacomo** [comment]
[`CCITT IA5`][1] is a 7-bit character code (encoded as 8 bits) similar to [`ASCII`][2]. Then, I suppose that an input string could be sanitized in dballe/wreport and the invalid characters (e.g. `ò à €`) could be replaced or ignored. After that, the string can be safely truncated using var length in bytes, because 1 byte = 1 char.

[1]: http://www.zytrax.com/tech/ia5.html
[2]: http://www.zytrax.com/tech/codes.htm

**Comment by pat1** [comment]
> CCITT IA5 is a 7-bit character code (encoded as 8 bits) similar to ASCII. Then, I suppose that an 
> input 
> string could be sanitized in dballe/wreport and the invalid characters (e.g. ò à €) could be replaced or 
> ignored. After that, the string can be safely truncated using var length in bytes, because 1 byte = 1 
> char.
I agree
Il problema secondo me è da scindere in due; 
primo: il bug fatale che interrompe la procedura che è docuto all'immissione di caratteri impropri; risolvibile non immettendo i caratteri impropi (sono attento e non lo faccio) o impedendone l'immissione (dballe da errore).
secondo: se esiste la necessità di utilizzare i set di caratteri estesi (utf8?) e se esiste trovare una soluzione per poterlo fare (questo coinvolge test e verifica di una serie di programmi connessi tra cui la libsim).
Risolverei uno e se esiste farei una richiesta di miglioramento della due

**Comment by spanezz** [comment]
If I give an error when calling `setc` for Fortran, or the equivalent in Python, there is a problem in that I only need to validate the string when the variable unit is CCITTIA5, and not otherwise, in order not to break the use case of setting binary values.

Implementing such a check in dballe would be rather costly. In wreport it's easier, as wreport internals know right away the difference between string and binary. However, I need to go through wreport's code to distinguish checked from unchecked operations, so that wreport can still decode a message with a non-7-bit-clean string variable.

This is all easier said than done. I'll now look for alternatives.

**Comment by spanezz** [comment]
Tests in branch `dballe8` pass with the wreport branch `dballeissue139`. You can try deploying that wreport branch where you run the script that generates those BUFRs and see if you get an error, and if anything else breaks.

**Comment by edigiacomo** [comment]
Ok, it raises an exception :ok_hand:

**Comment by spanezz** [comment]
Is there still something missing in this issue, or can it be closed?
