### ISSUE TITLE
Remove data using cursor of another DB and CursorDataDB.query

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/dballe#143]
I should implement a sort of intersection between two dbs and this is the cleanest way that I found:

    for row2 in db2.query_data({}):                                             
        with db1.transaction() as trans1:                                       
            q = {                                                               
                k: row2[k]                                                      
                for k in ("ident", "lon", "lat", "rep_memo",                    
                          "level", "trange", "datetime")                        
            }                                                                   
            q["var"] = row2["var"].code                                         
            for row1 in trans1.query_data(q):                                   
                if all([                                                        
                    row1["var"].enq() == row2["var"].enq(),                     
                    row1.attr_query() == row2.attr_query()                      
                ]):                                                             
                    trans1.remove_data(row1.query)                              
                else:                                                           
                    print(row1["var"].enq(), row2["var"].enq())

I cannot use `trans1.query_data(row2.query)`  because `row2.query` has `ana_id` instead of `ident, lon, lat, rep_memo`.

Is there a better way to convert the cursor to a query for another database?

**Comment by spanezz** [comment]
Since now we have `Cursor.remove()`, I can happily change `.query` to be database independent.

**Comment by edigiacomo** [comment]
Thank you! I'd like Python API to be as db independent as possibile.
