### ISSUE TITLE
dballe8 build in CentOS fails to compile Fortran interface

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/dballe#148]
In CentOS only, there are a lot of errors like:

```
Error: Binding label 'idba_query_data' in interface body at (1) collides with the global entity 'idba_query_data' at (2)
```

See https://travis-ci.org/ARPA-SIMC/dballe/jobs/472666360

**Comment by dcesari** [comment]
Evidentemente la versione vecchia di gfortran su Centos7 non accetta diversi binding fortran alla stessa funzione C, per cui ho dovuto ricorreggere all'indietro. Ho comunque potuto eliminare le varie `INTERFACE idba_<nomeinitaliano>_orig` perché sono usate solo internamente a dballef.f90 e quindi in quei casi chiamo direttamente la versione C col nome nuovo.
