### ISSUE TITLE
Database structure for mobile stations

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#150]
When investigating use cases for #147, I realised that one of the first significant uses of mobile stations in DB-All.e ended up partitioning fixed and mobile stations in two different databases.

If that is a hint of where things are going, I would be interested in implementing a different design for handling mobile stations inside a DB-All.e database, with two different table structures optimized for fixed or mobile stations.

Fixed stations would continue to be structured as they are now, with latitude and longitude connected to the station ID. Mobile stations would only have the ident connected to the station ID, and the coordinates would be moved together with the datetime: each time the station measures something, it is in a different place.

This would prevent the station table from exploding in size with one mobile stations per each datetime of measurement, and generally enable to manage mobile data in DB-All.e in a way that is designed for them, instead of being shoehorned into the design for fixed stations.

Setting `mobile=0` on insert would be a way to override if a station with a value for `ident` should be treated as a fixed station, in case it turns out that the current misuse has spread enough to need to be officially supported.

This will mean changing the behaviour of `ana_id` for *mobile* stations *only*: when querying data of mobile stations, `ana_id` will change only when `ident` will change, and will stay the same for different `lat`, `lon` values for the same `ident`. Also, it could be that a fixed station and a mobile station, although they are different, will share the same `ana_id`, because they will be generated by independent sequences.

If at these constraints can be ok, I could try to work on a prototype.

Note that nothing will change for a database that only contains fixed stations, or mobile stations forced to be imported as fixed. The different behaviour would only appear when mobile stations are imported as mobile.

**Comment by edigiacomo** [comment]
Ok for me, @brancomat, @pat1 and @dcesari.
