### ISSUE TITLE
f29 and rawhide copr build fails, errors on help2man

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/dballe#151]
```
+ make
COLUMNS=200 help2man --name='export data from DB-All.e' --section=1 --no-info --version-string="7.36" src/dbaexport > dbaexport.1
help2man: can't get `--help' info from src/dbaexport
Try `--no-discard-stderr' if option outputs to stderr
make: *** [Makefile:1023: dbaexport.1] Error 126
error: Bad exit status from /var/tmp/rpm-tmp.UOFD06 (%build)
```
from:
https://copr-be.cloud.fedoraproject.org/results/simc/stable/fedora-29-x86_64/00823865-dballe/builder-live.log

help2man error could be a consequence and not the cause, further details needed

**Comment by brancomat** [comment]
created internal server `ventinove` to diagnose f29 builds

**Comment by brancomat** [comment]
Of course on the internal server everything works

[dballe-7.36-f29-log.txt](https://github.com/ARPA-SIMC/dballe/files/2860490/dballe-7.36-f29-log.txt)

**Comment by dcesari** [comment]
src/dbaexport is a python script, so there is probably some issue with python, we could try to fix the Makefile.am to run src/dbaexport without help2man

**Comment by brancomat** [comment]
note: issue not present on travis builds.

**Comment by edigiacomo** [comment]
`help2man` invokes the command passed as argument, but in the `master` branch the script `src/dbaexport` has the shebang `#!/usr/bin/python`, which is not allowed in Fedora > 29.

In `dballe8` branch the script has the shebang `#!/usr/bin/python3` and its man page is built succesfully (https://copr-be.cloud.fedoraproject.org/results/simc/test/fedora-rawhide-x86_64/00844012-dballe/builder-live.log). We could close this issue when `dballe8` branch is merged in the `master` branch.

**Comment by edigiacomo** [comment]
In the Travis build for [Fedora 29][1], the `python` executable is found

```
checking for python... /usr/bin/python
checking for python version... 2.7
```

In the Copr build for [Fedora 29][2], the `python` executable is not found
```
checking for python... no
checking for python2... /usr/bin/python2
checking for python version... 2.7
```

In the Travis build the `#!/usr/bin/python` shebang works, whereas in Copr it doesn't.

[1]: https://travis-ci.org/ARPA-SIMC/dballe/jobs/493257634#L1753-L1754
[2]: https://copr-be.cloud.fedoraproject.org/results/simc/stable/fedora-29-x86_64/00858577-dballe/builder-live.log

**Comment by brancomat** [comment]
> In `dballe8` branch the script has the shebang `#!/usr/bin/python3` and its man page is built succesfully

as stated by @edigiacomo, issue fixed with the deploy of dballe 8, closing the issue
