### ISSUE TITLE
Python: add documentation for keywords available in cursor classes

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/dballe#155]
The keywords available in cursor classes (`CursorStationDB, CursorStationDataDB, CursorDataDB, CursorSummaryDB, CursorSummarySummary, CursorSummaryDBSummary, CursorMessage`) are not listed in the documentation.

Moreover, the documentation doesn't mention the `__getitem__` method (e.g. `cursor["lon"]`) available.

**Comment by spanezz** [comment]
The list of keywords available across all APIs should be here:
https://github.com/ARPA-SIMC/dballe/blob/master/doc/fapi_parms.md

I'll now look into documenting `__getitem__` on cursor

**Comment by spanezz** [comment]
This is still a bit basic, but it's a beginning. It's hard for me to evaluate the quality of documentation: if you let me know where/how you see the need of improvements, I can try to improve

**Comment by edigiacomo** [comment]
Thank you!

**Comment by spanezz** [comment]
Now this is at https://arpa-simc.github.io/dballe/parms.html

I still welcome input on what improvements would be needed: it's quite easy to work on that page.

**Comment by edigiacomo** [comment]
Thank you! The documentation is good enough for me now, I close this issue because it seems stale.
