### ISSUE TITLE
bufr2json --format=dballe do not output valid json

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#16]
with bufr2json --format=dballe "[" at beginning and "]" at the end are missed as "," as separator in the middle.

dbamsg dump --json  synop.bufr

{"version":"0.1","network":"synop","ident":null,"lon":1070000,"lat":4420000,"date":"2013-06-01T00:00:00Z","data":[{"timerange":[1,0,21600],"level":[1,null,null,null],"vars":{"B13011":{"v":0.0,"a":{"B07032":2.00}}}},{"timerange":[1,0,86400],"level":[1,null,null,null],"vars":{"B13011":{"v":0.0,"a":{"B07032":2.00}}}},{"timerange":[4,0,10800],"level":[1,null,null,null],"vars":{"B10060":{"v":-20,"a":{"B07031":2173.0}}}},{"timerange":[4,0,86400],"level":[1,null,null,null],"vars":{"B10060":{"v":100,"a":{"B07031":2173.0}}}},{"timerange":[205,0,10800],"level":[1,null,null,null],"vars":{"B10063":{"v":8,"a":{"B07031":2173.0}}}},{"timerange":[254,0,0],"level":[1,null,null,null],"vars":{"B10004":{"v":77230,"a":{"B07031":2173.0}},"B20001":{"v":30000,"a":{"B07032":2.00}}}},{"timerange":[254,0,0],"level":[100,85000,null,null],"vars":{"B10008":{"v":13651,"a":{}}}},{"timerange":[254,0,0],"level":[103,2000,null,null],"vars":{"B12101":{"v":276.15,"a":{}},"B12103":{"v":271.02,"a":{}},"B13003":{"v":69,"a":{}}}},{"timerange":[254,0,0],"level":[103,10000,null,null],"vars":{"B11001":{"v":350,"a":{"B07032":2.00}},"B11002":{"v":9.3,"a":{"B07032":2.00}}}},{"timerange":[254,0,0],"level":[256,null,258,0],"vars":{"B08002":{"v":8,"a":{}},"B20011":{"v":6,"a":{}},"B20013":{"v":1000,"a":{}}}},{"timerange":[254,0,0],"level":[256,null,258,1],"vars":{"B20012":{"v":30,"a":{}}}},{"timerange":[254,0,0],"level":[256,null,258,2],"vars":{"B20012":{"v":21,"a":{}}}},{"timerange":[254,0,0],"level":[256,null,258,3],"vars":{"B20012":{"v":10,"a":{}}}},{"timerange":[254,0,0],"level":[256,null,259,1],"vars":{"B08002":{"v":1,"a":{}},"B20011":{"v":6,"a":{}},"B20012":{"v":4,"a":{}},"B20013":{"v":1000,"a":{}}}},{"timerange":[254,0,0],"level":[256,null,null,null],"vars":{"B20010":{"v":75,"a":{}}}},{"vars":{"B01001":{"v":16,"a":{}},"B01002":{"v":134,"a":{}},"B01019":{"v":"MONTE_CIMONE","a":{}},"B02001":{"v":2,"a":{}},"B02002":{"v":12,"a":{}},"B05001":{"v":44.20000,"a":{}},"B06001":{"v":10.70000,"a":{}},"B07030":{"v":2165.0,"a":{}},"B07031":{"v":2173.0,"a":{}}}}]}
{"version":"0.1","network":"synop","ident":null,"lon":1185000,"lat":4346667,"date":"2013-06-01T00:00:00Z","data":[{"timerange":[1,0,21600],"level":[1,null,null,null],"vars":{"B13011":{"v":0.0,"a":{"B07032":2.00}}}},{"timerange":[1,0,86400],"level":[1,null,null,null],"vars":{"B13011":{"v":9.0,"a":{"B07032":2.00}}}},{"timerange":[4,0,10800],"level":[1,null,null,null],"vars":{"B10060":{"v":0,"a":{"B07031":249.0}}}},{"timerange":[4,0,86400],"level":[1,null,null,null],"vars":{"B10060":{"v":-10,"a":{"B07031":249.0}}}},{"timerange":[205,0,10800],"level":[1,null,null,null],"vars":{"B10063":{"v":4,"a":{"B07031":249.0}}}},{"timerange":[254,0,0],"level":[1,null,null,null],"vars":{"B10004":{"v":97600,"a":{"B07031":249.0}},"B20001":{"v":14000,"a":{"B07032":2.00}}}},{"timerange":[254,0,0],"level":[101,null,null,null],"vars":{"B10051":{"v":100540,"a":{"B07031":249.0}}}},{"timerange":[254,0,0],"level":[103,2000,null,null],"vars":{"B12101":{"v":285.35,"a":{}},"B12103":{"v":282.74,"a":{}},"B13003":{"v":84,"a":{}}}},{"timerange":[254,0,0],"level":[103,10000,null,null],"vars":{"B11001":{"v":0,"a":{"B07032":2.00}},"B11002":{"v":0.0,"a":{"B07032":2.00}}}},{"timerange":[254,0,0],"level":[256,null,258,0],"vars":{"B08002":{"v":7,"a":{}},"B20011":{"v":7,"a":{}},"B20013":{"v":840,"a":{}}}},{"timerange":[254,0,0],"level":[256,null,258,1],"vars":{"B20012":{"v":35,"a":{}}}},{"timerange":[254,0,0],"level":[256,null,258,2],"vars":{"B20012":{"v":20,"a":{}}}},{"timerange":[254,0,0],"level":[256,null,258,3],"vars":{"B20012":{"v":10,"a":{}}}},{"timerange":[254,0,0],"level":[256,null,259,1],"vars":{"B08002":{"v":1,"a":{}},"B20011":{"v":7,"a":{}},"B20012":{"v":6,"a":{}},"B20013":{"v":840,"a":{}}}},{"timerange":[254,0,0],"level":[256,null,null,null],"vars":{"B20010":{"v":88,"a":{}}}},{"vars":{"B01001":{"v":16,"a":{}},"B01002":{"v":172,"a":{}},"B01019":{"v":"AREZZO","a":{}},"B02001":{"v":2,"a":{}},"B02002":{"v":12,"a":{}},"B05001":{"v":43.46667,"a":{}},"B06001":{"v":11.85000,"a":{}},"B07030":{"v":248.0,"a":{}},"B07031":{"v":249.0,"a":{}}}}]}

**Comment by edigiacomo** [comment]
`JSON` format in `dballe` is a [Line Delimited JSON](https://en.wikipedia.org/wiki/Line_Delimited_JSON): every line is a generic message (and a valid `JSON`).

```
dbamsg dump --json | while read line ; do <someting with JSON string> ; done
```

`bufr2json` dumps an array of generic messages and must be fixed. I close the issue because the command is not part of this project.

**Comment by spanezz** [comment]
Per riferimento:
https://en.wikipedia.org/wiki/JSON_Streaming#Line_delimited_JSON
