### ISSUE TITLE
Fix importing of SHIP according to new level 161

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#162]
From https://github.com/ARPA-SIMC/dballe/pull/161:

Looking at the SHIP template who says "depth below sea surface" I think we need to change the importer to use level 161.

There seem to me no operational procedures that use that data at the moment, so it looks like we can do it with impunity.

To preserve consistency of being able to export previously imported data, I can look into both level 160 and 161 when exporting SHIP water temperatures.

**Comment by lidiabressan** [comment]
I don't have any applications using ship, so you can change the ship importer to use level 161.

**Comment by edigiacomo** [comment]
Sorry @spanezz have you done changes to the code to fix this issue?

**Comment by spanezz** [comment]
Good catch, I had missed the actual fix.

I have now updated the level from 160 to 161 in issue #162, which confused me for a moment when writing the commit message :)
