### ISSUE TITLE
add scale in table B in documentation

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#165]
If possible for reference on how to write integer values  add scale in table B in documentation:
https://www.conftool.pro/congressoaisam2019/index.php?page=browseSessions&presentations=show

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
