### ISSUE TITLE
Togliere context_id come parametro di query

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#17]
Quando si fanno query (voglioquesto, dimenticami), viene mai usato context_id?

Se non viene mai usato, vorrei dichiarare la feature ufficialmente non supportata.

**Comment by pat1** [comment]
mmm, io go presente ana_id e data_id; per quanto concerne data_id è utilizzata pesantemente nel controllo di qualità per ottimizzarele riscritture degli attributi.
Nelle ultime versioni vista la conplessità del suo utilizzo (specialmente ragionando ad oggetti), la sua non transazionalità stiamo facendo dei benchmark per verificare il calo di performance eliminandone l'utilizzo. Abbiamo dei problemi nella riscrittura solo degli attributi e non dei dati. Risolto questo e verificati i benchmark si potrà eliminare data_id.

**Comment by spanezz** [comment]
Se stai parlando di ```*data_id``` usata per gli attributi (voglioancora/critica/scusa), quella non ho intenzione di cambiarla.

Stavo parlando di usare ```context_id``` come uno dei vari filtri della ```voglioquesto```. È corretto assumere che sia una feature che al momento non viene proprio usata?

**Comment by pat1** [comment]
Bho, mi sono perso.
*data_id non so cosa sia

Sono a casa e mi mancano dei pezzi ma nelle api fortran 2003 io espongo ana_id che nelle api dballe fortran 77 dovrebbe corrispondere a context_id (context non mi piaceva e mi pareva una notazione interna a dballe).
https://github.com/ARPA-SIMC/libsim/blob/qcspa/vol7d/vol7d_dballe_class_dati.F90
linea 51
https://github.com/ARPA-SIMC/libsim/blob/qcspa/vol7d/vol7d_dballe_class.F03
linea 620

oltre alla vecchia versione fortran 77 in dismissione quando l'altra funzionerà completamente con gli attributi (vedi nota sopra)
vol7d_dballeold_class.F90

**Comment by pat1** [comment]
forse è per questo che non mi funziona!

**Comment by edigiacomo** [comment]
Io uso `context_id` per fare le query sugli attributi in Python:

```python
import dballe
db = dballe.DB.connect_from_file("db.sqlite")
# Prendo il primo dato
v = next(db.query_data(dballe.Record()))
# Prendo gli attributi del primo dato
a = db.attr_query_data(v["context_id"])
```

Oppure c'è un modo migliore che permette di evitare l'uso del `context_id`?

**Comment by spanezz** [comment]
Ripeto, *non sto parlando delle funzioni che lavorano con gli attributi*.

Sto parlando della voglioquesto o della query_data. Del fare roba tipo:
```
r = dballe.Record()
r["context_id"] = 42
for res in db.query_data(r): ...
```

Se parlare di ```context_id``` vi fa venire in mente solo gli attributi, allora direi che avete risposto alla mia domanda: nessuno lo usa in quel modo, posso farlo sparire. Noto che non era nemmeno documentato come parametro di query nella documentazione dell'API Fortran.

**Comment by pat1** [comment]
ok
e cosa sarebbe *data_id ?

**Comment by spanezz** [comment]
Tutte le chiavi con un asterisco all'inizio vengono lette solo dalle funzioni che gestiscono gli attributi, che non sono oggetto di questo ticket. Qui mi riferisco solo all'input delle funzioni che fanno query di dati.

Direi che ho avuto le conferme che cercavo, grazie a tutti e due.
