### ISSUE TITLE
python documentation

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#170]
I look here
https://arpa-simc.github.io/dballe/python/dballe_cursors.html
All the cursors are described as "A Cursor is the result of database queries. "
Here https://arpa-simc.github.io/dballe/python/dballe_db.html# I found the query that return the different cursors.
I think that a link from cursor to query and vice versa will be an improvement as an a better (but short description) of query.

The use of "standard" word well defined should be better as:
* station
* data
* data attributes
* constant station data
* constant station data attributes
we use those naming in other documentation ...

in python dballe documentation I found:
* Query the station archive in the database
* Query the variables in the database
* query data attributes
* Query the station variables in the database
* query station data attributes

**Comment by spanezz** [comment]
I crosslinked cursor documentation with the matching query methods, and I fixed the names you mentioned where I could find them.

I'm closing this issue. If you see more naming issues or other documentation issues, please keep opening bugs and pointing to where the issues are.

Thanks for this review, it's very valuable.
