### ISSUE TITLE
datetimes parameter in `dbaexport` not working anymore

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/dballe#174]
in dballe-8.3-1:
```
$ dbadb wipe --dsn=sqlite://pippo.sqlite
$ dbaexport --verbose --dsn=sqlite://pippo.sqlite --outfile tmp.csv csv yearmin=2019 monthmin=10 daymin=15 hourmin=0 minumin=0 secmin=0 yearmax=2019 monthmax=10 daymax=16 hourmax=0 minumax=0 secmax=0
/usr/bin/dbaexport:38: DeprecationWarning: please use connect instead of connect_from_url
  return dballe.DB.connect_from_url(url)
Traceback (most recent call last):
  File "/usr/bin/dbaexport", line 115, in <module>
    dballe.dbacsv.export(db, query, fd)
  File "/usr/lib/python3.7/site-packages/dballe/dbacsv.py", line 391, in export
    e.output(query, fd)
  File "/usr/lib/python3.7/site-packages/dballe/dbacsv.py", line 357, in output
    self.compute_columns(self.tr, query)
  File "/usr/lib/python3.7/site-packages/dballe/dbacsv.py", line 293, in compute_columns
    for row in tr.query_data(filter):
TypeError: datetime value must be an instance of int, or None
```
Apparently, date parameters arrive as strings here:
https://github.com/ARPA-SIMC/dballe/blob/10bcd57ccd00d91e2caa772af2cb5f95854102cf/python/dballe/dbacsv.py#L293

```
{'yearmin': '2019', 'monthmin': '10', 'daymin': '15', 'hourmin': '0', 'minumin': '0', 'secmin': '0', 'yearmax': '2019', 'monthmax': '10', 'daymax': '16', 'hourmax': '0', 'minumax': '0', 'secmax': '0'}
```

(it would be great to add a `dbaexport` test in the test suite)

**Comment by spanezz** [comment]
I supposed previously there was some automatic casting that was lost in recent refactorings. Good idea to add tests for `dbaexport`: it used to be mostly a prototype to see if it would be useful, and if it is useful, we can promote it past prototype stage and add tests and everything

**Comment by brancomat** [comment]
with the current master (dballe 8.4-1) the issue is still present (and not in the test suite I guess)

```
$ dbadb wipe --dsn=sqlite:tmp.sqlite
$ dbaexport --dsn=sqlite:tmp.sqlite --outfile tmp.csv csv yearmin=2019 monthmin=11 daymin=06 hourmin=03 yearmax=2019 monthmax=11 daymax=06 hourmax=10
/usr/bin/dbaexport:38: DeprecationWarning: please use connect instead of connect_from_url
  return dballe.DB.connect_from_url(url)
Traceback (most recent call last):
  File "/usr/bin/dbaexport", line 115, in <module>
    dballe.dbacsv.export(db, query, fd)
  File "/usr/lib/python3.7/site-packages/dballe/dbacsv.py", line 391, in export
    e.output(query, fd)
  File "/usr/lib/python3.7/site-packages/dballe/dbacsv.py", line 357, in output
    self.compute_columns(self.tr, query)
  File "/usr/lib/python3.7/site-packages/dballe/dbacsv.py", line 293, in compute_columns
    for row in tr.query_data(filter):
TypeError: datetime value must be an instance of int, or None
```

**Comment by spanezz** [comment]
What was tested and fixed was the handling of incomplete datetime values. Now it seems it doesn't like datetime values to be strings. I'll investigate.

**Comment by brancomat** [comment]
Thanks, confirming that it's now working.

What I meant with the comment about the test suite was:
a `dbadb wipe` to create an empty db and a `dbaexport` on it using many (if not all) query parameters generating a "Result is empty." response with no other errors is the kind of test I was expecting to be already present in the test suite, since it covers a bunch of very basic functions that are expected to always work.

Though this is probably a topic for another issue.
