### ISSUE TITLE
python api: summaries return few values

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#176]
[dballe_report_fixed.sqlite.zip](https://github.com/ARPA-SIMC/dballe/files/3741465/dballe_report_fixed.sqlite.zip)

query:
{'ident': None, 'lon': 1069920, 'lat': 4452372, 'rep_memo': 'simnpr', 'pindicator': 254, 'p1': 0, 'p2': 0, 'leveltype1': 103, 'l1': 2000, 'leveltype2': None, 'l2': None, 'var': 'B12101', 'yearmin': 2017, 'yearmax': 2017, 'monthmin': 4, 'monthmax': 4, 'daymin': 18, 'daymax': 19, 'hourmin': 0, 'hourmax': 20, 'minumin': 0, 'minumax': 59, 'secmin': 0, 'secmax': 59}

response:
{'ident': None, 'lon': 1069920, 'lat': 4452372, 'rep_memo': 'simnpr', 'level': (103, 2000, None, None), 'trange': (254, 0, 0), 'var': 'B12101', 'datemin': datetime.datetime(2017, 4, 18, 23, 30), 'datemax': datetime.datetime(2017, 4, 18, 23, 30)}

datemin and datemax are wrong

**Comment by spanezz** [comment]
How are you performing the query, and how are you printing the response?

In other words, could you give me a short python program that reproduces the issue with that database?

Also, could you give me the correct values of `datemin` and `datemax` that you are expecting?

**Comment by pat1** [comment]
not so easy because summaries have strange behaviour.
 import dballe

```
db = dballe.DB.connect_from_file("dballe_report_fixed.sqlite")

query = {'ident': None, 'lon': 1069920, 'lat': 4452372, 'rep_memo': 'simnpr', 'pindicator': 254, 'p1': 0, 'p2': 0, 'leveltype1': 103, 'l1': 2000, 'leveltype2': None, 'l2': None, 'var': 'B12101', 'yearmin': 2017, 'yearmax': 2017, 'monthmin': 4, 'monthmax': 4, 'daymin': 18, 'daymax': 19, 'hourmin': 0, 'hourmax': 20, 'minumin': 0, 'minumax': 59, 'secmin': 0, 'secmax': 59}

with db.transaction() as t:
    for cur in t.query_summary(query):
        print(cur["lat"],cur["lon"])
        print(cur["trange"])
        print(cur["level"])
        print(cur["variable"])
```
but with key taken from documentation at "Parameters used when reading query results for summary values"
print(cur['yearmin'])
print(cur["datetimemin"])
print(cur["variable"])

I get :
 KeyError: 'key <thekey> not found on this query result'

**Comment by spanezz** [comment]
I have fixed the parameter documentation, removing `variable` (which shouldn't have been there) and documenting that min/max datetime information is only available when using `query=details`.

I then changed your example to this:
```
#!/usr/bin/python3
        
import dballe
        
db = dballe.DB.connect_from_file("dballe_report_fixed.sqlite")
        
query = {'ident': None, 'lon': 1069920, 'lat': 4452372, 'rep_memo': 'simnpr',
         'pindicator': 254, 'p1': 0, 'p2': 0, 'leveltype1': 103, 'l1': 2000,
         'leveltype2': None, 'l2': None, 'var': 'B12101',
         'yearmin': 2017, 'monthmin': 4, 'daymin': 18, 'hourmin': 0, 'minumin': 0,
         'yearmax': 2017, 'monthmax': 4, 'daymax': 19, 'hourmax': 20, 'minumax': 59,
         'secmin': 0, 'secmax': 59, "query": "details"}

with db.transaction() as t:
    print("Summary:")
    for cur in t.query_summary(query):
        print(cur["lat"], cur["lon"])
        print(cur["trange"])
        print(cur["level"])
        print(cur["datetimemin"])
        print(cur["datetimemax"])
    
    print("Data:")
    for cur in t.query_data(query):
        print(cur["datetime"])

```
I think this reproduces the issue, where querying `datetimemin` would return `datetimemax` instead. I'll now fix it.
