### ISSUE TITLE
python api: 'dballe.CursorSummaryDB' object has no attribute 'copy'

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#179]
Come posso migrare il codice che in dballe 7 conteneva:

 dballe.CursorSummaryDB.copy()

credo il metodo fosse disponibile per tutti i cursori.

**Comment by edigiacomo** [comment]
Non ricordo esattamente i casi d'uso (immagino sia in rmap), forse non è più necessario il `copy()` ?

**Comment by pat1** [comment]
è usato frequentemente in borinud

**Comment by edigiacomo** [comment]
Prova a toglierlo, potrebbe non essere più necessario. E nel caso di CursorStation e CursorData forse si potrebbe usare `.data`

**Comment by pat1** [comment]
a cosa servisse .copy precedentemente non ne ho idea.
chiudo la issue
