### ISSUE TITLE
quantesono/elencamele: documentazione risultati attesi

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#18]
Al momento, per una quantesono/elencamele il numero di stazioni risultanti cambia a seconda dei database:
 * per i database ```mem:```, c'è una stazione per ogni combinazione di (report, lat, lon, ident)
 * per i database basati su sql, c'è una stazione per ogni combinazione di (lat, lon, ident)

L'ordinamento delle stazioni nel risultato al momento non è definito: i database basati su SQL ordinano per ana_id, il database ```mem:``` non mi è chiaro per cosa ordini al momento, ma mi sembra dipenda dalla query che viene fatta.

In future implementazioni di database basati su SQL, vorrei andare nella direzione di una stazione per ogni combinazione di (report, lat, lon, ident), come nel database ```mem:```.

Per l'ordinamento, vorrei documentare che i risultati non sono ordinati.

Mi confermi che questo coincide con la realtà di come DB-All.e è usato al momento?

**Comment by pat1** [comment]
Usando il db mem: ho già dovuto risolvere una serie di bug dovuti a questo cambiamento (vedi branch QC di libsim) andando nella direzione una stazione per ogni combinazione di (report, lat, lon, ident).
Questo per quanto riguarda libsim, poi ci sono gli altri software.

**Comment by spanezz** [comment]
Ok, direi che anche una futura versione dello storage basato su SQL avrà stazioni distinte per ogni (report, lat, lot, ident).

Riguardo l'ordinamento, mi confermi che non c'è niente che fa affidamento su un ordine specifico delle stazioni che escono da una quantesono/elencamele?

**Comment by pat1** [comment]
per quanto io conosco si

**Comment by spanezz** [comment]
Ho aggiunto alla documentazione della quantesono:

> There is no guarantee on the ordering of results of quantesono/elencamele.
