### ISSUE TITLE
adding python api examples for use of Explorer

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#181]
Some examples for use of Explorer will be very useful.

**Comment by spanezz** [comment]
Could you give me some use cases or example problems that can serve as themes for Explorer examples?

**Comment by pat1** [comment]
I do not know what is explorer so it's just philosophy

Now:
* put data in DB
* query summaries
* query data

using the example should be:
* put data in DB and add data to explorer
* query explorer
* query data

or
* put data in DB
* put data in DB
* ...
* build explorer
* query explorer
* query data

**Comment by edigiacomo** [comment]
Un caso d'uso di cui avevamo discusso è il seguente:

* BUFR archiviati in Arkimet sono passati, con il `--copyok/--moveok`, in una directory dove viene generato il loro summary in JSON con uno script basato su API Python di dballe e il summary JSON viene "fuso" con quello del giro precedente
* Un secondo script basato su API Python di dballe che permette di:
  * Fare query sul summary (e.g. `var=B12101 pindicator=1`)
  * Fare query su summary per poi scaricare solo i BUFR delle stazioni che fanno match (in modo da sfruttura la granularità del summary su var, level, trange che in Arkimet non c'è)

**Comment by spanezz** [comment]
Dopo qualche giro di domande:

* nella procedura di importazione di arkimet, viene mantenuto un summary dei contenuti di un dataset arkimet, o di piú dataset arkimet
* è possibile usare quel summary per esplorare il contenuto del dataset
* per passare da un filtro dell'explorer all'estrazione di dati, vengono estratti tutti i BUFR filtrati per stazione/datetime, e poi filtrati ulteriormente uno per uno col resto della query

**Comment by spanezz** [comment]
Ho aggiunto un paio di esempi in `doc/python_how/explorer.rst`: siamo sulla strada giusta?

**Comment by pat1** [comment]
Come creo un explorer da un dsn e lo salvo in json ?

**Comment by pat1** [comment]
eravamo sulla strada giusta, ma ora sembra che si sia un blocco stradale da qualche tempo ... ;)
le domande qui sopra sono poco chiare ?
come posso chiarire per procedere con lo sviluppo che non può più aspettare ?

**Comment by pat1** [comment]
Relativamente alle terza domanda Wikipedia relativamente a Xapian dice:
Simultaneous search and update, with new documents being immediately visible.
quindi la risposta è si se uso Xapian e forse no se uso json ?

**Comment by spanezz** [comment]
Ho committato in master le cose a cui potevo rispondere aggiungendo esempi.

Non capisco cosa intendi per "ottimizzare l'update".

Puoi sia aggiungere explorer a explorer esistenti che crearne dei nuovi, come preferisci.

Se usi json, quando crei l'Explorer il file .json viene letto in memoria, e quando esci dal `with explorer.update(): …` il file .json viene riscritto da zero in modo atomico. Questo vuol dire che puoi fare letture concorrenti alle scritture quanto vuoi, ma:
* se fai due scritture concorrenti, vince l'ultima e la prima viene sovrascritta
* se apri un explorer e i file .json viene sovrascritto da una scrittura, in memoria mantieni i dati che hai letto all'apertura.

Se usi database Xapian, allora puoi fare letture e una scrittura tutti assieme come dice. Se non è cambiato qualcosa di recente, Xapian come sqlite non supporta due aperture in scrittura allo stesso momento. Supporta comunque quante aperture in lettura vuoi, e fino a una scrittura in contemporanea alle letture.

Questo risponde fin qui alle tue domande?

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
