### ISSUE TITLE
Salvare nel DB un riferimento alla tabella usata

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#185]
Per evitare cambio di significato dei dati se si accede allo stesso DB con versioni diverse di DB-All.e, salvare nel DB un'informazione sul `dballe.txt` presa da una costante definita a tempo di compilazione. Se il valore nel DB non corrisponde al valore nel codice, dare un warning o rifiutarsi di aprire il file.

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
