### ISSUE TITLE
date in insert record

### ISSUE THREAD

**Issue by lidiabressan** [ARPA-SIMC/dballe#187]
A little question: before the last version, it was possible (and very easy to use) to insert a date in a record with a datetime.datetime object, while now I have to specify all integers year, month, day, hour, minute, second. It is possible to re-add this, please?

```
rec = {
    'lat':float(lat),
    'lon':float(lon),
    'report':report,
    'level':level,
    'trange':trange,
    #'date':data_dato,
    'year':data_dato.year,
    'month':data_dato.month,
    'day':data_dato.day,
    'hour':data_dato.hour,
    'min':data_dato.minute,
    'sec':data_dato.second,
    }
 rec[dballe_var] = dato
 db.insert_data(rec, can_replace=can_replace, can_add_stations=True)
```
thanks
ciao

**Comment by spanezz** [comment]
Good catch! You can use `datetime`, `level`, and `trange`, but they were missing in the documentation. I'll add them now.
