### ISSUE TITLE
not clear explanation of get method of var

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#188]
https://arpa-simc.github.io/dballe/python/dballe_types.html
```
 get(default: Any=None) → Union[str, float, long, Any]
    get the value of the variable, with a default if it is unset
```
"with a default if it is unset" cosa significa ? Un default valore o un default tipo ? Quando è unset cosa? La var o il parametro del metodo? Ma il parametro del metodo cosa è?

**Comment by spanezz** [comment]
I have changed the documentation in wreport to this:
```
get the value of the variable. If the variable is unset, ``default`` is returned
```
Would this be clear enough?

**Comment by pat1** [comment]
non mi è ancora chiaro cosa dovrei passare alla funzione oltre al default None

**Comment by edigiacomo** [comment]
Il valore che vorresti avere al posto di `None` quando la var è unset.

```python
import dballe
var = dballe.var("B13011", None)
var.get() is None # True
var.get("valore mancante") == "valore mancante" # True
var.get(0) == 0 # True
```

**Comment by pat1** [comment]
Ma quindi per specificare il tipo tornato da get devo passare il parametro default ?
Nel caso per non cambiare il default "di default" dovrei sapere quale è mi pare per poter specificare solo il tipo; probabilmente è None se capisto la simbologia della documentazione.
E se non passo default che tipo torna?

**Comment by edigiacomo** [comment]
Se non specifichi il valore del parametro `default`, usa il default di default che è appunto il valore `None`. Se invece hai specificato un valore di default, ti restituisce quello.

La annotazione del metodo (la simbologia della documentazione) dice che puoi usare un valore di qualsiasi tipo.

Se non sai il tipo della var, credo che tu lo possa sapere da https://arpa-simc.github.io/dballe/python_ref/types.html#dballe.Varinfo.type

Credo che l'idea fosse di copiare la semantica di [dict.get](https://docs.python.org/3/library/stdtypes.html?highlight=get#dict.get), quindi un modo abbastanza comune di fare le cose in Python.

**Comment by pat1** [comment]
grazie delle spiegazioni, ma la domanda a quale tipo torna era riferita nel caso di dato presente:
una temperatura di 273.15 K che tipo torna senza default ?
E se la volessi come stringa con valore di default None cosa devo scrivere ?
E se la volessi come intero con valore di default None cosa devo scrivere ?

**Comment by edigiacomo** [comment]
Se il valore è settato, ti restituisce il valore con il tipo associato alla var, cioè numeric, stringa etc. Nel caso di una temperatura, quindi, un float.

Il default è usato

**Comment by edigiacomo** [comment]
Scusa, il telefono mi è impazzito e ho chiuso la issue per errore, oltre che inviare un messaggio incompleto.

Il metodo `get` restituisce il valore usando il tipo della var (vedi https://arpa-simc.github.io/dballe/python_ref/types.html#dballe.Varinfo.type), il `default` ti serve solo se il valore non è settato.

Se voi forzare il tipo restituito, usi `enqc`, `enqd`, `enqi`.

**Comment by pat1** [comment]
Io metterei in documentazione:
```
l metodo get restituisce il valore usando il tipo della var (vedi https://arpa-simc.github.io/dballe/python_ref/types.html#dballe.Varinfo.type)
Perforzare il tipo restituito, usare enqc, enqd, enqi
```
poi dballe.Varinfo.type non so da dove venga preso, ma penso possa essere determinato solo da due categorie (prima: string; seconda: binary, integer, decimal) e forse tra i tipi binary, integer, decimal c'è un default ?

**Comment by edigiacomo** [comment]
Il tipo della var è dedotto da alcuni "indizi": se è `CCITTIA5` allora è stringa, altrimenti se la scala è 0 è un intero altrimenti è un decimale. Il binario credo che sia un fallback per codici sconosciuti - chiedo a @spanezz conferma.

Faccio una PR (in wreport) e vi chiederò una revisione.

**Comment by spanezz** [comment]
Mi ero perso la PR, l'ho approvata ora. Chiudo il ticket
