### ISSUE TITLE
ordinamento in voglioquesto/dammelo

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#19]
Facendo review del codice ho notato comportamenti incoerenti nell'ordinamento dei risultati della voglioquesto/dammelo, e ho aggiunto test per verificarli. Al momento lo stato è questo:

Database ```memdb```:
 * coordinate, ident, datetime, level, timerange, varcode, report

Database SQL:
 * ana_id, datetime, level, timerange, report, varcode

Ordinare per ana_id nei db SQL significa solo che i dati sono raggruppati per coordinate e ident, ma l'ordine dei gruppi non è definito.

In teoria, l'ordinamento nel caso dei database SQL sarebbe da correggere scambiando report e varcode.

In pratica però, siccome mantenere questi ordinamenti è costoso in termini di performance, e se tutto al momento sta funzionando con ordinamenti piú scarpazzoni, vorrei ridefinire i requisiti di ordinamento con qualcosa che permetta ai software di funzionare e lasci piú libertà possibile alle implementazioni di DB-All.e.

Per esempio, possiamo distinguere raggruppamenti e ordinamenti, e dire che i dati siano *raggruppati* per (coordinate, ident) invece di *ordinati* per (coordinate, ident).

Stesso discorso per level e timerange: serve un ordinamento, o basta un raggruppamento? In caso di raggruppamento, serve raggruppare per livello e poi raggruppare per timerange tutti i dati con lo stesso livello, o basta raggruppare per combinazioni uniche di livello e timerange?

Riguardo all'ordinamento/raggruppamento per report, come viene usato? All'inizio l'idea era di avere per ogni variabile in un certo punto+istante, tutti i suoi valori report per report, ma visto che l'implementazione per i database SQL al momento rompe questo vincolo, mi chiedo: questo vincolo serve, o potrei invece, per esempio, raggruppare tutto per (report, coordinate, ident) invece che per (coordinate, ident)?

Quanto è possibile rilassare tutto questo? Possiamo decidere che i dati vengano restituiti in ordine sparso? Qual è il minimo requisito di raggruppamento / ordinamento necessario a far funzionare i programmi che usano DB-All.e?

**Comment by pat1** [comment]
per quanto mi ricordo i vincoli iniziali erano che l'ordinamento fosse per ana_id(coordinate, ident), time e l'ultimo a scorrere fosse var.
Quello che c'è in mezzo non credo abbia molta importanza.
In sostanza fa comodo avere tutte le variabili a metadati costanti .
Memdb rompe questa cosa.
Quali applicazioni siano influenzate difficile da dire ...

Vol7d riordina tutto sigolarmente senza raggruppamenti e abbiamo dedicato tempo a ottimizzare il sort, ma avere la dimensione più grande già ordinata credo velocizzi di molto. Solitamente le dimensioni più grandi sono ana_id e time.

Mi riservo ulteriori approfondimenti.

**Comment by spanezz** [comment]
Ho pushato la fix a memdb, cosí ora non rompe piú questa cosa

**Comment by pat1** [comment]
c'è qualche cosa che osta a chiudere questo bug?

**Comment by spanezz** [comment]
Lo tengo aperto finché non ho trasposto tutto nella documentazione.

**Comment by spanezz** [comment]
Ho aggiunto questo in documentazione: va bene?

> Results are sorted by (in order): latitude, longitude, ident, datetime, level, time range, rep_memo, varcode. The latitude changes slowest, and the varcode changes fastest.
> Note that in V6 databases the ana_id corresponds to (latitude, longitude, ident), and therefore changes slowest, and in MEM and V7 databases the ana_id corresponds to (latitude, longitude, ident, rep_memo), and therefore changes almost the fastest.
> Sort order can change in the future, with the invariant that the slowest to change remains (coordinates, ident) and the fastest to change remains the varcode.

**Comment by pat1** [comment]
Scusa, riapro il bug sulla questione rep_memo.
la frase:
```
Note that in V6 databases the ana_id corresponds to (latitude, longitude, ident), and therefore changes slowest, and in MEM and V7 databases the ana_id corresponds to (latitude, longitude, ident, rep_memo), and therefore changes almost the fastest.
```
non mi risulta chiara.
Su questo anche io ho fatto una affermazione con leggerezza: 
```che l'ordinamento fosse per ana_id(coordinate, ident), time e l'ultimo a scorrere fosse var.```
Si riferiva infatti al passato.
Questo oggi infatti è sbagliato in quanto è ana_id(coordinate, ident, rep_memo).
E' probabile che quindi sia meglio spostare rep_memo nell'ordinamento appena dopo latitude, longitude, ident

Cosa ne pensi?

**Comment by spanezz** [comment]
Molto volentieri: se importa il raggruppamento piú dell'ordinamento, questo mi permetterebbe anche di ordinare semplicemente per ana_id senza coinvolgere 4 campi.

La documentazione diventerebbe:

> Results are sorted by (in order): ana_id, datetime, level, time range, varcode. The ana_id changes slowest, and the varcode changes fastest.
> Ordering by ana_id effectively does grouping by station rather than ordering.
> Note that in V6 databases the ana_id corresponds to (latitude, longitude, ident), and does not include rep_memo, so in V6 databases the ordering is effectively "ana_id, rep_memo, datetime, level, time range, varcode".
> Sort order can change in the future, with the invariant that the slowest to change remains ana_id and the fastest to change remains the varcode.
￼
torna?

**Comment by pat1** [comment]
l'unica correzione sarebbe questa:
```
Sort order can change in the future, with the invariant that the slowest to change remains ana_id 
and the fastest to change remains the varcode.
```
```
Sort order can change in the future, with the invariant that the slowest to change remains ana_id, 
after  datetime
and the fastest to change remains the varcode.
```
Se va bene lascio aperto per l'implementazione

**Comment by spanezz** [comment]
Perfetto.

**Comment by pat1** [comment]
Forse mi sono dimenticato dell'utilizzo relativo alle stazioni mobili.
Seguendo l'attuale ordinamento un volo d'aereo (tenendo fissa l'ident quindi) risulta ordinato per coordinate, poi per il tempo ...
Seguire quindi l'evoluzione di un parametro di una stazione mobile nel tempo e quindi nello spazio richiede un riordinamento;

Un tale cambiamento non ho chiaro cosa comporti:
* lavoro di implementazione (molto/poco)
* cambio delle performance ?
* cambio degli applicativi
* altro ?

Se facciamo una veloce valutazione sarà poi possibile decidere se è preferibile implementare l'ordinamento negli applicativi che visualizzano stazioni mobili.

**Comment by spanezz** [comment]
Puoi per favore aprire un nuovo bug invece di far partire una discussione in un bug chiuso da agosto?

**Comment by pat1** [comment]
aperta #83
