### ISSUE TITLE
dbamsg dump --csv --interpreted 

### ISSUE THREAD

**Issue by lidiabressan** [ARPA-SIMC/dballe#193]
ciao,
is it possible to not export all the report, year, month, day, hour, minute, second, lon and lat as if it were variables, please? Just skipping these rows?

example output for every datum:
```
"longitude","latitude","report","date","level","l","level","l","time rang","p","p","varcod","value"
12.39482,44.77840,"a500m",,,,,,,,,B01194,"a500m"
12.39482,44.77840,"a500m",,,,,,,,,B04001,2018
12.39482,44.77840,"a500m",,,,,,,,,B04002,9
12.39482,44.77840,"a500m",,,,,,,,,B04003,30
12.39482,44.77840,"a500m",,,,,,,,,B04004,1
12.39482,44.77840,"a500m",,,,,,,,,B04005,0
12.39482,44.77840,"a500m",,,,,,,,,B04006,0
12.39482,44.77840,"a500m",,,,,,,,,B05001,44.77840
12.39482,44.77840,"a500m",,,,,,,,,B06001,12.39482
12.39482,44.77840,"a500m","2018-09-30 01:00:00",101,,,,254,0,0,B22038,0.166
```
thanks
Lidia

**Comment by dcesari** [comment]
non escludo che si possa fare con una v7d_transform --output-format dbacsv
che esce con un formato compatibile

Il 22/nov/2019 10:57 AM, "lidiabressan" <notifications@github.com> ha
scritto:

**Comment by lidiabressan** [comment]
anche sui file sqlite?
adesso faccio:
dbadb export --dsn=sqlite:file | dbamsd dump --csv --interpreted

**Comment by pat1** [comment]
v7d_transform legge direttamente da un dsn dballe
