### ISSUE TITLE
parameters for query_stations?

### ISSUE THREAD

**Issue by lidiabressan** [ARPA-SIMC/dballe#198]
ciao,
Are the query parameters for query_stations the same as for all queries? It seems so in the documentation.
However, if I restrict the time ranges in the query with the query parameters yearmin, monthmin, daymin, hourmin, minumin, secmin, I still get all db stations. Should it work this way? It would be very useful if the query could select only stations with data corresponding to the query. Or am I falling in the bug with yearmin, monthmin, ecc? I only use x-min parameters.
Let me know, thanks!
ciao
Lidia

**Comment by spanezz** [comment]
`query_stations` works only on station data, and so far has never touched measured values. You are right that the query argument documentation does not distinguish between which query is done, although they don't all make sense in all queries: for example, it doesn't make sense to query a station height by datetime.

I'll now try to update the parameter documentation to have this distinction.

Meanwhile, if you need to query stations filtered by the period in which they have data, please turn this issue into a feature request

**Comment by spanezz** [comment]
I expanded the query parameters documentation to cover the `query_stations`, `query_station_data` and the other `query_*` cases

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
