### ISSUE TITLE
dbadb export doesn't parse properly the missing value "-"

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/dballe#200]
The `-` should be interpreted as "missing value", but it seems that it doesn't work anymore.

(Attached [input.bufr.gz](https://github.com/ARPA-SIMC/dballe/files/3916810/input.bufr.gz))

```
$ dbadb import --dsn=sqlite:test.db --wipe-first input.bufr
$ dbadb export --dsn=sqlite:test.db | dbamsg dump --interpreted
#0[0] generic message, 44.60016,12.07738, dt: 2019-01-01T00:00:00, 2 contexts:
Level -,-,-,-, tr -,-,-,
001019 LONG STATION OR SITE NAME(CCITTIA5): Camse
001194 Report mnemonic(CCITTIA5): locali
004001 YEAR(YEAR): 2019
004002 MONTH(MONTH): 1
004003 DAY(DAY): 1
004004 HOUR(HOUR): 0
004005 MINUTE(MINUTE): 0
004006 SECOND(SECOND): 0
005001 LATITUDE (HIGH ACCURACY)(DEGREE): 44.60016
006001 LONGITUDE (HIGH ACCURACY)(DEGREE): 12.07738
007030 HEIGHT OF STATION GROUND ABOVE MEAN SEA LEVEL (SEE NOTE 3)(M): -1.0
007031 HEIGHT OF BAROMETER ABOVE MEAN SEA LEVEL (SEE NOTE 4)(M): 0.0
Level 103,2000,-,-, tr 254,0,0
012101 TEMPERATURE/DRY-BULB TEMPERATURE(K): 285.15
$ dbadb export --dsn=sqlite:test.db leveltype2=- | wc -c
0
```

Related issue: #29

**Comment by spanezz** [comment]
Ora `-` è di nuovo parsato come missing. Ricordo che settare un parametro di query come missing ha l'effetto di non filtrare su quel parametro, e non di selezionare i record che hanno valori mancanti in quel parametro.

**Comment by edigiacomo** [comment]
Pensavo che fosse una naturale conseguenza: se imposto e.g. `leveltype1=1 l1=-` mi sarei aspettato di avere un oggetto-query diverso da `leveltype1=1` e di conseguenza una query diversa. 

Apro issue nuova come enhancement - ma prima la assegno a noi del SIMC per capire se sono solo io che vorrei un comportamento del genere.
