### ISSUE TITLE
how to use python api for messages

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#205]
I think will be useful an example to change content of an existing dballe.Message

this example try to change 'report' but it do not works
```
import dballe

importer = dballe.Importer("BUFR")
exporter = dballe.Exporter(encoding="BUFR")

with open("out.bufr", "wb") as fp:
    with importer.from_file("temp.bufr") as f:
        for msgs in f:
            for msg in msgs:
                print (msg)
                msg.set_named("report", dballe.var("B01194", "sound"))
                print("{m.report},{m.coords},{m.ident},{m.datetime},{m.type}".format(m=msg))

                fp.write(exporter.to_binary(msg))

```
```
Traceback (most recent call last):
  File "convertmessages.py", line 8, in <module>
    msg.set_named("report", dballe.var("B01194", "sound"))
KeyError: "Shortcut name 'report' not found"
```
Is possible to have a working example?

**Comment by edigiacomo** [comment]
The problem here is that the _shortcut_ `report` doesn't exist, you can use `rep_memo`.

@spanezz this is caused by the lack of this shortcut in `dballe/vars.csv`, right? In this case, it's possibile to add the shortcuts to the documentation? I can open another issue if you want.

**Comment by pat1** [comment]
I suggest to remove rep_memo everywhere and use "report" only or "network" as alias

**Comment by spanezz** [comment]
I added `report` and `network` shortcuts in aad7c2f521b82b940971c1fac50b93b2569d0733
