### ISSUE TITLE
json format usable in fortran interface?

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/dballe#215]
Since, AFAIU, now json is a full-right citizen among the dballe formats, could we use it natively also from the fortran interface for reading/writing files, e.g. in [`idba_messages_open_input`](https://github.com/ARPA-SIMC/dballe/blob/801d88fd24f71fee4143dff3063f18857e6fceae/fortran/binding.cc#L1321) & c, together with bufr and crex?

**Comment by spanezz** [comment]
Yes, definitely: you use "JSON" instead of "BUFR" as the format argument.

I just added a Fortran test to make sure it is: https://github.com/ARPA-SIMC/dballe/blob/master/fortran/check_messages_json.f90
