### ISSUE TITLE
explorer show different result updating from db or file

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#216]
attched a sample program and data that create an explorer from db (temperature), update from a db (humidity), update with the same humidity but from file.
Importing from file show more varcodes:
```
python explorerfromdb.py
created from DB
[dballe.Level(103,2000,None,None)]
[dballe.Trange(254,0,0)]
['B12101']
ExplorerStats(datetime_min=datetime.datetime(2020, 7, 3, 0, 0), datetime_max=datetime.datetime(2020, 7, 3, 14, 0), count=8212)
updated from DB
[dballe.Level(103,2000,None,None)]
[dballe.Trange(254,0,0)]
['B12101', 'B13003']
ExplorerStats(datetime_min=datetime.datetime(2020, 7, 3, 0, 0), datetime_max=datetime.datetime(2020, 7, 3, 23, 45), count=16846)
updated from file
[dballe.Level(103,2000,None,None), None]
[dballe.Trange(254,0,0), None]
['B01011', 'B01194', 'B04001', 'B04002', 'B04003', 'B04004', 'B04005', 'B04006', 'B05001', 'B06001', 'B12101', 'B13003']
ExplorerStats(datetime_min=datetime.datetime(2020, 7, 3, 0, 0), datetime_max=datetime.datetime(2020, 7, 3, 23, 45), count=104903)
```
[explorer.zip](https://github.com/ARPA-SIMC/dballe/files/4874604/explorer.zip)

**Comment by spanezz** [comment]
At a glance it looks surprising. Here is what is going on:

* Importing from the json file uses `import_messages` that acts like importing messages in a database, which inserts both station values and measured values.
* Importing from a database runs `query_summary`, which works either on station values or on measured values, depending on the query.

The general idea is that if dballe is reading from a file containing messages, be them BUFR or JSON, it needs to do everything in one pass, so it takes in all the data it can. If it's reading from a database, one can use a query to control what is read.

If this is not the behaviour you expect, we need to either talk about what dballe should do, or figure out where and how to document what is going on.

**Comment by pat1** [comment]
The question is:
how I can have the same behaviour of  update from DB when updating from file ?
Loading file in tmp DB to update explorer from DB do not seems to me a good solution while working with a lot of data...

**Comment by spanezz** [comment]
I understand that, when updating from a file, you would like to get *only* a summary of *measured* data, without station values. Is that correct?

**Comment by pat1** [comment]
yes, 
something like:
import_messages(constant_station_data=True,station_data=True)
can be a compatible interface.
(note that "constant station data" , "station data" are the standard name)
