### ISSUE TITLE
problema con dbadb delete

### ISSUE THREAD

**Issue by amontani** [ARPA-SIMC/dballe#22]
se cerco di cancellare con "dbadb delete", ho questo errore:

dbadb delete attr_filter="B33007<50"
--dsn='mysql://localhost:3306/soglie?user=vpavan&password=80qwfwq'
cannot execute 'DELETE FROM data WHERE id IN ()':You have an error in
your SQL syntax; check the manual that corresponds to your MariaDB
server version for the right syntax to use near ')' at line 1 

Che dire?
Grazie e ciao.
   Andrea

**Comment by spanezz** [comment]
Sistemato in b56c1830bbb8ba28c0a1486b198f234857becdca
