### ISSUE TITLE
jsonline importer do not take in account offsets from UTC in date field

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#221]
ISO_8601 define offset from UTC
https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC

jsonline file content:
```
{"date":"2020-07-02T15:10:00+02:00","lat":4457611,"lon":1171154,"network":"fidu","data":[{"vars":{"B01019":{"v":"Accursi Idice"},"B07030":{"v":18.0},"B07031":{"v":17.0}}},{"level":[103,0,null,null],"timerange":[254,0,0],"vars":{"B13215":{"v":82.100000000000009}}},{"level":[103,0,null,null],"timerange":[254,0,0],"vars":{"B13215":{"v":0.0}}}]}
```
results:
```
dbamsg dump -t json  --interpreted tmp.jsonline 
#0[0] generic message, 44.57611,11.71154, dt: 2020-07-02T15:10:00, 2 contexts:
Level -,-,-,-, tr -,-,-,
001019 LONG STATION OR SITE NAME(CCITTIA5): Accursi Idice
001194 Report mnemonic(CCITTIA5): fidu
004001 YEAR(YEAR): 2020
004002 MONTH(MONTH): 7
004003 DAY(DAY): 2
004004 HOUR(HOUR): 15
004005 MINUTE(MINUTE): 10
004006 SECOND(SECOND): 0
005001 LATITUDE (HIGH ACCURACY)(DEGREE): 44.57611
006001 LONGITUDE (HIGH ACCURACY)(DEGREE): 11.71154
007030 HEIGHT OF STATION GROUND ABOVE MEAN SEA LEVEL (SEE NOTE 3)(M): 18.0
007031 HEIGHT OF BAROMETER ABOVE MEAN SEA LEVEL (SEE NOTE 4)(M): 17.0
Level 103,0,-,-, tr 254,0,0
013215 River level(M): 0.00
```

**Comment by edigiacomo** [comment]
The JSON parser supports only the formats `YYYY-mm-ddTHH:MM:SS` and `YYYY-mm-dd HH:MM:SS`. In my opinion it's better to keep things as simple as possibile: I assume that every program that is able to use a specific timezone is able to convert a datetime to UTC.

**Comment by pat1** [comment]
ISO_8601 is the RMAP specification.
No problem for me but we have to release a new version of RMAP specification defining what is supported and what not

**Comment by edigiacomo** [comment]
> ISO_8601 is the RMAP specification.

I understand your point but ISO 8601 is a broad standard and I think that if we add the timezone then we will support a subset of the standard anyway.

Maybe it's better to explicitly state the datetime formats currently supported.

**Comment by spanezz** [comment]
I agree to stick with datetimes in UTC in JSON, and I don't think it's reasonable to go and implement timezone handling, simplified or otherwise, in dballe.

If you want to accept JSONs with more complex datetimes, you can preprocess them in python, where you have access to a broader range of libraries that handle timezones properly, and convert them to UTC.

**Comment by pat1** [comment]
concordo, però se le specifiche son sono quelle iso bisogna specificare quali specifiche sono.
Ossia da qualche parte dobbiamo scrivere come si scrive la data: le specifiche sono più volte specifiche oggetto di gara e devono essere definite in modo preciso.

**Comment by edigiacomo** [comment]
As I previously said, if we add the timezone then we will support a subset of the standard anyway. E.g. 2020-01 is a valid ISO8601 date. Then, we need to explicitly state the supported datetime formats in any case.

If it's ok, we can close this and open two issues:

- Document the supported datetime formats
- The datetime parser could be more strict and raise an error when trailing chars are found in the string

**Comment by spanezz** [comment]
Aperto il primo su #229

**Comment by spanezz** [comment]
Aperto il secondo su #230. Chiudo questo issue continuandolo negli altri due.
