### ISSUE TITLE
implementation of != for attr_filter

### ISSUE THREAD

**Issue by lidiabressan** [ARPA-SIMC/dballe#223]
When I invalidate data, I add the attribute {'B33196':1} to the invalid data, without adding the attribute to valid data.
It would be very useful to filter these data with the query:  attr_filter="B33196!=1". I believe that now it is not implemented.

Thanks!

Lidia

**Comment by spanezz** [comment]
You mean that `attr_filter="B33196!=1"` should also match those variables that do not have a `B33196` set?

Indeed now if there's an `attr_filter` for an attribute, it skips all variables that do not have that attribute, no matter what the filter is.

I think it makes sense. @edigiacomo, @pat1, are you ok with this?

**Comment by pat1** [comment]
you suggest that if I call tools for delete with attr_filter="B33196!=1" a get a DB with only data with  B33196=1 ?
If yes, I agree

**Comment by lidiabressan** [comment]
I suggest that if I call tools to get data with attr_filter="B33196!=1", I get all data data with B33196=0 and with the attribute B33196 missing.

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
