### ISSUE TITLE
unexpected behaviour of != for attr_filter

### ISSUE THREAD

**Issue by lidiabressan** [ARPA-SIMC/dballe#224]
!= seems not to be implemented for attr_filter. 
When I tried to do a query with attr_filter="B33196!=1", the output were only data with B33196=1.  Shouldn't give an error instead?

dbadb export attr_filter="B33196!=1"  --dsn=sqlite:test_raw.sqlite3 | dbadb --wipe-first import --dsn=sqlite:test_clean.sqlite3

[test.zip](https://github.com/ARPA-SIMC/dballe/files/4902784/test.zip)

**Comment by spanezz** [comment]
Ho aggiunto alla documentazione dei parametri di query una sezione apposta sulla sintassi di questi filtri, e ho sistemato il caso del `!=`, che prima era gestito solo come `<>`
