### ISSUE TITLE
Problems in writing json from Fortran

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/dballe#226]
I implemented json format in libsim; decoding works well, but encoding inserts an empty line between each line with a message, thus a successive read interprets only the first message. Maybe we are misusing the fortran API?

I attach the bufr input, the json output obtained and the trace of the operations done in fortran.

[json_fortran.zip](https://github.com/ARPA-SIMC/dballe/files/4904076/json_fortran.zip)

**Comment by spanezz** [comment]
I should have fixed this yesterday in fbcd412fd38007d91ea9766eb387acdc930d5e52, while I added the Fortran test
