### ISSUE TITLE
consecutive data in query_data loop

### ISSUE THREAD

**Issue by lidiabressan** [ARPA-SIMC/dballe#227]
ciao!

I need some advice to invalidate consecutive data (also 20 or 30 data) with the same value.

I would generally read data, check if my datum has the same value of the previous ones, in case remember the first datum and after the last one add the invalid attribute to all signed data. By cycling on data, I know which data to invalidate only after the last one, so I need to go back for x data.

How can I do it with dballe and dballe cursors in a query_data loop? Do you have some suggestions?

Thanks!

Lidia

**Comment by edigiacomo** [comment]
I just found a possibile solution: you can save the reference to the invalid data (see `context_id` in https://arpa-simc.github.io/dballe/general_ref/parms/output.html#parameters-used-when-reading-query-results-for-station-values) in a list and then invalidate them in a second loop.

Something like this:

```
invalid_list = []
prev = None
with db.transaction() as tr:
    for row in tr.query_data(....):
        value = row["variable"].get()
        if prev == value:
            invalid_list.append(row["context_id"])

        prev = value

    for ctxid in invalid_list:
        tr.attr_insert_data(ctxid, {"B33196": 1})
```
