### ISSUE TITLE
Document the supported datetime formats

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#229]
This is related to #221. There is a need to document the subset of ISO8601 that we support for dates in JSON and possibly CSV.

What are the current places where this is documented and might cause confusion?

**Comment by spanezz** [comment]
Note, in #230 I added support for an optional trailing Z

**Comment by pat1** [comment]
I have to document it here:
https://doc.rmap.cc/rmap_rfc/rfc.html#json
this is the base documentation for some projects and other official documents ...

**Comment by spanezz** [comment]
I documented the whole JSON format in 936d8158dfbd138c4b82842c5763d3f350363038, including the datetime format.

The documentation is linked under 'general reference'
