### ISSUE TITLE
Raccogliere un po' di dati sull'uso di database in produzione

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#23]
Con il commit 9fd88f8e34d8a289716685b34866b21e0fcaee5d ho finito di implementare il logging su stderr dell'analisi delle query che vengono fatte al database.

Se si lancia un programma che usa DB-All.e settanto la variabile di ambiente `DBA_EXPLAIN=1`, su stderr compariranno tutte le query fatte al database, i parametri di query corrispondenti di DB-All.e, e un'analisi della query fatta dal database.

Sarebbe possibile far girare con `DBA_EXPLAIN=1` un po' di procedure significative effettivamente usate in produzione, e mandarmi il loro standard error?

Vorrei usare queste informazioni per vedere se effettivamente il database (e i suoi indici) sono stati strutturati in un modo che effettivamente corrisponde alle esigenze reali di utililzzo.

**Comment by brancomat** [comment]
Circa ma sarà un percorso lungo, in prima battuta alla prima ricompilazione di dballe possiamo farlo per le proc in test preoperativo (quality control) e casi studio (verifica) sulle quali modifiche a indici e struttura hanno anche effetti più rilevanti.
Altre procedure operative rilevanti (kalman filter) girano su versioni obsolete di dballe e necessitano di riscrittura. 
Il resto al momento usa db sqlite volatili su cui non credo valga la pena di investire in ottimizzazioni (vanno già a scheggia).
Lascio aperto il bug e lo aggiorno appena ho news.

**Comment by brancomat** [comment]
Primi feedback su verifica cosmo leps (driver mysql) by https://github.com/amontani
[dballog_ver_interpola.txt](https://github.com/ARPA-SIMC/dballe/files/63897/dballog_ver_interpola.txt)
[dballog_ver_scores_prob.txt](https://github.com/ARPA-SIMC/dballe/files/63898/dballog_ver_scores_prob.txt)

**Comment by brancomat** [comment]
Ulteriori feedback purtroppo non positivi su confronto mysql / postgresql by https://github.com/amontani


> ho rigirato il caricamento dei previsti (il task che impiega piu` tempo) per 3 giorni, settando DBA_EXPLAIN=1.
> Il log file è allegato

[test_postgres.txt](https://github.com/ARPA-SIMC/dballe/files/104579/test_postgres.txt)

questa la tabella riassuntiva del confronto, già Umberto aveva riscontrato un aumento dei tempi nell'inserimento dati osservati che avevamo ritenuto accettabile ma con i previsti cambia decisamente l'ordine di grandezza

```
=====================================
Verification features of cosmo-leps:
16 members;
2 months;
2 forecast ranges;
1824 stations (1612 for scores);
4 thresholds;


                 mysql                  postgres

caricamento
osservati         8 min                 18 min

caricamento
dati previsti    43 min                 41 h

calcolo degli
scores            3 min                 4 min

         ---------------------------------------------
                ~54 min                ~ 41h 22 min
=====================================
```

**Comment by spanezz** [comment]
On Tue, Jan 26, 2016 at 12:04:07AM -0800, Daniele Branchini wrote:

>    questa la tabella riassuntiva del confronto, giÃ  Umberto aveva
>    riscontrato un aumento dei tempi nell'inserimento dati osservati che
>    avevamo ritenuto accettabile ma con i previsti cambia decisamente l'ordine
>    di grandezza
[...]
>                   mysql                  postgres
>  caricamento
>  osservati         8 min                 18 min
>  caricamento
>  dati previsti    43 min                 41 h
>  calcolo degli
>  scores            3 min                 4 min
>           ---------------------------------------------
>                  ~54 min                ~ 41h 22 min

Quale versione di postgres avete usato?


Enrico

-- 
GPG key: 4096R/E7AD5568 2009-05-08 Enrico Zini <enrico@enricozini.org>

**Comment by amontani** [comment]
Ciao Enrico,
   ecco la info:


rpm -q postgresql
postgresql-9.3.6-1.fc20.x86_64


A presto.
  Andrea


Il 31/01/2016 15:46, spanezz ha scritto:
> On Tue, Jan 26, 2016 at 12:04:07AM -0800, Daniele Branchini wrote:
>
>  > questa la tabella riassuntiva del confronto, giÃ  Umberto aveva
>  > riscontrato un aumento dei tempi nell'inserimento dati osservati che
>  > avevamo ritenuto accettabile ma con i previsti cambia decisamente
> l'ordine
>  > di grandezza
> [...]
>  > mysql postgres
>  > caricamento
>  > osservati 8 min 18 min
>  > caricamento
>  > dati previsti 43 min 41 h
>  > calcolo degli
>  > scores 3 min 4 min
>  > ---------------------------------------------
>  > ~54 min ~ 41h 22 min
>
> Quale versione di postgres avete usato?
>
>
> Enrico
>
> --
> GPG key: 4096R/E7AD5568 2009-05-08 Enrico Zini <enrico@enricozini.org>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ARPA-SIMC/dballe/issues/23#issuecomment-177514538>.
>

-- 
Andrea Montani, MSc, PhD
Arpae Emilia-Romagna
Servizio Idro-Meteo-Clima
Viale Silvani 6
40122 Bologna
ITALY
*************************************
tel. +39 051 525928
fax. +39 051 6497501
*************************************
e-mail: amontani@arpa.emr.it
*************************************

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
