### ISSUE TITLE
Standard names for constant/station/measured data/values 

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#231]
For the standard names I currently refer to https://github.com/ARPA-SIMC/dballe/blob/master/doc/general_ref/concepts.rst

I recall we discussed standard names, but I don't recall if that file has been updated to reflect our discussion. I cannot find the notes of the meeting in which we had this discussion.

In #216, @pat1 said:

> (note that "constant station data" , "station data" are the standard name)

While `concepts.rst` uses "station values" and "values".

I'd like the help of you all to make sure you're all in agreement about the names that were decided, or that we should use, for these concepts, and then go on and fix the documentation and possibly some of the APIs.

**Comment by pat1** [comment]
Importante è uniformarsi.
Personalmente uso da tempo
"station data"
"constant station data" 
"network"
"lat"
"lon"
"ident"
"level"
"timerange"
"var"
"attribute"

anche su network abbiamo qualche schizzofrenia?
l'uso di values al posto di data mi lascia un poco perplesso...

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
