### ISSUE TITLE
report/network only lowercase?

### ISSUE THREAD

**Issue by lidiabressan** [ARPA-SIMC/dballe#236]
I noticed that report names become all lowercase. Should it be like this?
There is nothing in the documentation, I looked in general concepts (and there, in Station, there is still the old name rep_memo).

**Comment by spanezz** [comment]
In #30, it was supposed to be case insensitive. Then in some cases it was dependent on the database backend. In #153 it was supposed to be case sensitive. The implementation seems to reflect the uncertainty.

In theory I'd like to document what the code does. In practice, in this case we should start from documenting what the code should do, and fix the code accordingly.

I'll involve the others: let's take a decision and stick to it.

Options that come to my mind:
1. all case sensitive (inserting `Foo` stores `Foo` and matches `Foo` only)
2. case preserved but matched insensitively (inserting `Foo` stores `Foo` and matches `Foo`, `foo`, `FOO` and so on)
3. all case insensitive and normalised to lowercase (inserting 'Foo' stores `foo` and matches `Foo`, `foo`, `FOO` and so on)

Discuss! :)

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.

**Comment by brancomat** [comment]
IMHO this is still relevant, ambiguous and undocumented.
If nobody has strong opinions about this I'd vote for:

> 3\. all case insensitive and normalised to lowercase (inserting 'Foo' stores `foo` and matches `Foo`, `foo`, `FOO` and so on)

This would be also similar to the default behaviour of Libsim (see: https://github.com/ARPA-SIMC/dballe/issues/153#issuecomment-534045002)

Rather than leaving the issue stale I'm assigning this issue to @spanezz to implement and document this.
