### ISSUE TITLE
explorer and query_station return lat e lon scaled differently

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#247]
```
#!/usr/bin/python3
import dballe

# Create from database
db = dballe.DB.connect("sqlite:db.sqlite")
with dballe.Explorer("explorer") as explorer:
    with explorer.rebuild() as updater:
        with db.transaction() as tr:
            updater.add_db(tr)
    for staz in explorer.stations:
        print(staz.ident,staz.lat,staz.lon,staz.report) 

with db.transaction() as tr:
    for cur in tr.query_stations():
        print (cur["ident"]
               ,cur.enqi("lat")
               ,cur.enqi("lon")
               ,cur["report"]
        )
```
output :

```
...
None 44.1382 12.24364 urbane
None 44.22039 12.04182 urbane
None 44.415 12.20003 urbane
None 44.50075 11.32879 urbane
None 44.65639 10.91699 urbane
None 44.69781 10.6337 urbane
None 44.808 10.33049 urbane
None 44.8325 11.62114 urbane
None 45.05492 9.67965 urbane
....
dancast78 4449217 1137634 fixed
None 4604228 1186880 mnw
None 4570832 1186685 mnw
None 4586151 1134316 mnw
None 4455914 1097716 mnw
None 4577000 1172000 mnw
None 4466188 1185224 mnw
None 4473040 1218604 mnw
```

**Comment by pat1** [comment]
ossia dovendo usare lat e lon come chiavi non vorrei avere problemi di troncamento facendo divisioni e moltiplicazioni

**Comment by spanezz** [comment]
Non ho capito il problema: mi sembra che lette come interi, sia lat che lon escano moltiplicati per 10^5 come richiesto.

Se serve usare lat e lon come chiavi di qualcosa, l'ideale è usare la versione intera, che è pensata proprio per evitare i problemi classici del confronto fra valori floating point.

Però, in tutto questo, non mi è chiaro quale sia il problema che stai avendo: puoi essere piú specifico?

**Comment by pat1** [comment]
staz.lat e staz.lon  paiono essere float e non interi, questo per me è il problema e non vorrei essere io a fare la conversione non sapendo come farla correttamente

**Comment by spanezz** [comment]
Ah, capito. Quindi servirebbe poter accedere a lat e lon per le stazioni anche come interi. Implemento

**Comment by spanezz** [comment]
Ho aggiunto gli accessor `ilat` e `ilon` per gli oggetti `Station`, che restituiscono interi
