### ISSUE TITLE
Compatibility with python 3.9

### ISSUE THREAD

**Issue by mdantonio** [ARPA-SIMC/dballe#248]
Hello, I was trying to use the dballe from python 3.9 but we got several segmentation fault errors. Is python 3.9 not yet supported?
Is it planned to be supported with next versions?

**Comment by edigiacomo** [comment]
Fedora 33 ships Python 3.9 and the master branch builds successfully (https://travis-ci.org/github/ARPA-SIMC/dballe/jobs/753014267) - but the last version (8.14-1) should work too - as you can infer from the commit history https://github.com/ARPA-SIMC/dballe/compare/v8.14-1..master.

However, we will release a new version as soon as possibile.

**Comment by mdantonio** [comment]
Ok, thank you. So that, we will retry with the next version (8.15?) just to be sure about the full compatibility and then if it will still continue to fail we will go more in deep on the causes

**Comment by brancomat** [comment]
Version 8.15 has been released. Please retry with that version, if the problems persist we'll need some test case / example of the issue to investigate.
