### ISSUE TITLE
Skin temperature

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/dballe#249]
We need to use the variable "Skin temperature" from the WMO standard tables; as for other temperature-related variables, it is available with 2 B table codes with different precisions:
```
012061 Skin temperature                                                 K                          1            0  12 C                         1         3
012161 Skin temperature                                                 K                          2            0  16 C                         2         4
```
while in `dballe.txt` we have only the lower precision one 12061. Can we replace 12061 with 12161 in `dballe.txt`, to improve precision or we risk to break something?

**Comment by edigiacomo** [comment]
As far as I know, we don't use B12061 and then you can safely remove it.

**Comment by pat1** [comment]
mi pare non venga utilizzata dai decodificatori dei vari template, quindi mi pare corretto provvedere alla sostituzione.
Dovremo però prima o poi affrontare il problema di versionare la tabella ...
