### ISSUE TITLE
Documentazione in formati diversi da LaTeX

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#25]
Uno dei requisiti iniziali era che la documentazione di DB-All.e fosse in LaTeX. Questo però richiede che per far build di DB-All.e serva avere installato tutto LaTeX (e la distribuzione di latex usata per far build della roba prodotta da doxygen è piuttosto grossa), e al momento non stiamo usando formule o altre cose per cui LaTeX eccelle. Oltre a questo, per la generazione di HTML al momento stiamo usando latex2html che non è software libero.

È possibile rilassare questo requisito, e portare la documentazione a un formato piú leggero tipo markdown o restructuredText?

**Comment by dcesari** [comment]
On 23/11/2015 12:57, spanezz wrote:
> Uno dei requisiti iniziali era che la documentazione di DB-All.e fosse
> in LaTeX. Questo però richiede che per far build di DB-All.e serva avere
> installato tutto LaTeX (e la distribuzione di latex usata per far build
> della roba prodotta da doxygen è piuttosto grossa), e al momento non
> stiamo usando formule o altre cose per cui LaTeX eccelle. Oltre a
> questo, per la generazione di HTML al momento stiamo usando latex2html
> che non è software libero.
>
> È possibile rilassare questo requisito, e portare la documentazione a un
> formato piú leggero tipo markdown o restructuredText?

Per me va bene. Se posso dire la mia, reStructuredText mi sembra un po' 
troppo farcito di features da diventare difficile avere un controllo 
sull'output, d'altra parte il markdown ha i suoi dialetti regionali che 
confondono le acque. Io personalmente dopo il passaggio a github, sto 
tendendo al markdown per gli appunti documentativi vari così si possono 
mettere direttamente nel wiki github e, con un po' di attenzione, anche 
usare come pagine doxygen a se' stanti.
	D.

**Comment by edigiacomo** [comment]
Se posso dire la mia, anche io sto passando a Markdown, abbandonando pian piano Asciidoc (meglio di Markdown, ma integrazione limitata in GitHub e assente in Doxygen) e reStructuredText (che proprio non sopporto).

**Comment by brancomat** [comment]
+1 per Mardkown
(magari accordandosi prima su una qualche doc da prendere come testo sacro per aggirare il problema dei dialetti che diceva Davide)

**Comment by pat1** [comment]
io su questo sono ignorante e mi adeguo, ma le dipendenze da latex disturbano anche me

**Comment by spanezz** [comment]
Io intanto per facilitare il lavoro ho creato questo:
https://github.com/spanezz/mdpreview

**Comment by edigiacomo** [comment]
Bellissimo!

**Comment by spanezz** [comment]
Sto andando avanti con la conversione, attenendomi a un sottoinsieme di markdown supportato sia da GitHub che da Python-Markdown

**Comment by spanezz** [comment]
Fatto in f4143247. Date un'occhiata [qui](doc/fapi.md)

**Comment by dcesari** [comment]
Ottimo, fa veramente i bambini coi baffi! Capisco bene che parsi anche gli xml interni di doxygen per estrarre le API fortran? interessante...

**Comment by spanezz** [comment]
:) si, volevo generare la reference a tutti i binding partendo dal sorgente dei binding, e ho provato a farlo con l'xml, cosí delego a doxygen il parsing dei sorgenti e la raccolta della documentazione, e genero io la reference in markdown con l'indice sopra e gli `<a name="nomefunzione">` in modo che si possa linkare da ovunque con #nomefunzione alla fine.

**Comment by spanezz** [comment]
Ho migliorato il generatore di documentazione, ora la reference è piú completa e ha link interni.
