### ISSUE TITLE
Problema di build con gcc 10.2.1

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#252]
Provando a far build di dballe su debian testing, mi scoppia cosí:

```
gfortran -Ifortran/libdballef.so.5.0.0.p -Ifortran -I../fortran -I. -I.. -Idballe/libdballe.so.8.0.0.p -I/usr/include/lua5.1 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Wextra -Wpedantic -fimplicit-none -g -O2 -ffile-prefix-map=/home/enrico/lavori/arpa/dballe=. -fstack-protector-strong -fPIC -Jfortran/libdballef.so.5.0.0.p -o fortran/libdballef.so.5.0.0.p/dballef.f90.o -c ../fortran/dballef.f90
../fortran/dballef.f90:56:2:

   56 |   FUNCTION idba_disconnect(dbahandle) BIND(C,name='idba_disconnect')
      |  1
Error: Symbol ‘idba_disconnect’ at (1) has no IMPLICIT type; did you mean ‘idba_connect_orig’?
../fortran/dballef.f90:63:2:

   63 |   FUNCTION idba_arrivederci(dbahandle) BIND(C,name='idba_arrivederci')
      |  1
Error: Symbol ‘idba_arrivederci’ at (1) has no IMPLICIT type
../fortran/dballef.f90:618:2:

  618 |   FUNCTION idba_error_set_callback(code, func, dat, handle) BIND(C,name='idba_error_set_callback')
      |  1
Error: Symbol ‘idba_error_set_callback’ at (1) has no IMPLICIT type; did you mean ‘idba_remove_all’?
../fortran/dballef.f90:628:2:

  628 |   FUNCTION idba_default_error_handler(debug) BIND(C,name='idba_default_error_handler')
      |  1
Error: Symbol ‘idba_default_error_handler’ at (1) has no IMPLICIT type
../fortran/dballef.f90:635:2:

  635 |   FUNCTION idba_default_error_handle_tolerating_overflows(debug) BIND(C,name='idba_default_error_handle_tolerating_overflows')
      |  1
Error: Symbol ‘idba_default_error_handle_tolerating_overflows’ at (1) has no IMPLICIT type
```

Non riesco a capire la cosa: mi puoi aiutare?

**Comment by spanezz** [comment]
Ora ho questo problema anche con gfortran 8.3.0

**Comment by dcesari** [comment]
Nel pomeriggio ci guardo

**Comment by pat1** [comment]
io non riesco a riprodurre.
Fedora 32 
gfortran --version
GNU Fortran (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1)

**Comment by dcesari** [comment]
Però in effetti non ha tutti i torti, manca la definizione del risultato delle funzioni:

```
INTERFACE
  FUNCTION idba_disconnect(dbahandle) BIND(C,name='idba_disconnect')
  IMPORT
  INTEGER(kind=c_int) :: dbahandle
  END FUNCTION idba_disconnect
END INTERFACE
```

cioè il tipo di `idba_disconnect` stessa non è definito, delle due mi pare strano che abbia sempre compilato, ora non ricordo quale debba essere il tipo ritornato, immagino un int C, per cui la cosa corretta da fare dovrebbe essere modificarlo così:

```
INTERFACE
  FUNCTION idba_disconnect(dbahandle) BIND(C,name='idba_disconnect')
  IMPORT
  INTEGER(kind=c_int) :: dbahandle
  INTEGER(kind=c_int) :: idba_disconnect
  END FUNCTION idba_disconnect
END INTERFACE
```

e così via, come in effetti è fatto per alcune (`idba_fatto` per esempio).
Purtroppo, come dice Paolo, su Fedora 32 non si riproduce, per cui non riesco a verificare, ma dovrebbe essere corratta così.

**Comment by dcesari** [comment]
con `-Wall` da un non molto intellegibile:

```
Warning: Implicitly declared BIND(C) variable ‘idba_arrivederci’ at (1) may not be C interoperable [-Wc-binding-type]
dballef.f90:619:2:
```

che scompare con la dichiarazione di cui sopra.

**Comment by pat1** [comment]
Confermo Davide
Avendo il file un implicit none non si capisce come faccia a compilare con le nostre versioni di fortran
Ipotizzavo una dichiarazione implicita per l'interfaccia con C ma non mi pare sia definita dal fortran:
https://gcc.gnu.org/onlinedocs/gfortran/Interoperable-Subroutines-and-Functions.html#Interoperable-Subroutines-and-Functions
Però in rete ho visto esempi senza dichiarazione ... tipo qui http://prace.it4i.cz/sites/prace.it4i.cz/files/files/fort-04-2016c_interop.pdf dove res nel primo esempio non è dichiarato.

**Comment by spanezz** [comment]
Perfetto, grazie! Aggiungendo i tipi dei risultati come hai scritto tu mi compila.

Credo che la differenza tra me e voi è che compilo usando meson invece di autotools, e meson quando gli dico "sii pignolo coi compilatori" è in grado di propagare la preferenza anche a gfortran, cosa che in autotools forse va fatta a mano
