### ISSUE TITLE
idba_remove_all(handle) not documented in fapi

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#26]
non trovo documentazione

**Comment by pat1** [comment]
trovato questo nel codice C++
 /**
     * Remove orphan values from the database.
     *
     * Orphan values are currently:
     * \li lev_tr values for which no data exists
     * \li station values for which no lev_tr exists
     *
     * Depending on database size, this routine can take a few minutes to execute.
     */

**Comment by spanezz** [comment]
Fatto in f4143247.

Ora è [qui](../tree/master/doc/fapi_reference.md#idba_remove_all).
