### ISSUE TITLE
dbadb with -f return Duplicate entry for key 'id_station'

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#27]
https://github.com/r-map/rmap/issues/78

**Comment by pat1** [comment]
anche se risolto sul server rmap mi pare una situazione da indagare.
i dsn della versione dballe6 dovrebbero essere compatibili con dballe7 ?
se la risposta è no, si può chiudere il bug.

**Comment by spanezz** [comment]
Non ho capito la domanda e il bug non ha istruzioni per cercare di riprodurlo.

**Comment by pat1** [comment]
l'errore era questo:
mqtt2bufr -t rmap/# -t mobile/# |dbadb import -f --dsn=rmap
executing precompiled query:23000 [MySQL][ODBC 5.2(w) Driver][mysqld-5.5.43-MariaDB]Duplicate entry '6363-2016-01-17 11:11:06-1937-256-469' for key 'id_station'
che è difficile da riprodurre perchè era una scrittura con dballe 7 su un DB creato con dballe 6.
mqtt2bufr è un software che genera bufr tramite dballe.

Ne seguiva una domanda:
i dsn della versione dballe6 dovrebbero essere compatibili con dballe7 ?
se la risposta è no, si può chiudere il bug.

Altrimenti lo chiudiamo comunque e aspettiamo che si ripresenti.

**Comment by spanezz** [comment]
Dipende da come è stato creato il database. In 2de726ccfd04344969d6cf9ed07615c1ead18938 ho aggiunto il comando `dbadb info` che dà informazioni sul formato del database. Se a un certo punto riesci a lanciarlo su quel database, possiamo vedere se ci si può aspettare compatibilità oppure no.

**Comment by pat1** [comment]
non riproducibile
