### ISSUE TITLE
dballe fapi: do not use stdin/stdout with filename ""

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#28]
https://github.com/ARPA-SIMC/libsim/issues/10

**Comment by spanezz** [comment]
When the file name is empty, it should use stdin/stdout.

**Comment by spanezz** [comment]
In a69cef39e0479af77c042e709ce7202a490c8c79 I added a command fortran/check_messages_stdinstdout implemented in Fortran that copies one message from stdin to stdout, and it works for me, so I cannot reproduce this problem.

Can you please give me a simple test case that reproduces the issue?

**Comment by pat1** [comment]
was a libsim bug
