### ISSUE TITLE
source of Debian package?

### ISSUE THREAD

**Issue by simevo** [ARPA-SIMC/dballe#283]
Now that the official DB-All.e Debian package in the testing distribution mentioned in the README [is gone](https://bugs.debian.org/1029761), what is the source of the Debian package distributed from https://simc.arpae.it/packages/debian/ ?

I can't find the find the `ubuntu/jammy`, `debian/bullseye` and `debian/sid` branches mentioned in #277 ...

**Comment by edigiacomo** [comment]
> I can't find the find the `ubuntu/jammy`, `debian/bullseye` and `debian/sid` branches mentioned in #277 ...

```
$ git clone https://github.com/ARPA-SIMC/dballe.git
$ cd dballe
$ git branch --remote | grep '\(debian\|ubuntu\)'
  origin/debian/bullseye
  origin/debian/sid
  origin/ubuntu/jammy
```

Am I missing something?

**Comment by simevo** [comment]
:blush: oh so you are only publishing from `ubuntu/jammy`, [this changelog](https://github.com/ARPA-SIMC/dballe/blob/ubuntu/jammy/debian/changelog) matches version 9.5.2 [here](https://simc.arpae.it/packages/debian/pool/main/d/dballe/)

but the ubuntu jammy (LTS) package does not install on Debian stable:

```
docker run --rm -it debian:bookworm bash
apt update
apt install -y ca-certificates
echo "deb [trusted=yes] https://simc.arpae.it/packages/debian jammy main" > /etc/apt/sources.list.d/arpae-simc.list
apt update
apt install dballe python3-dballe libdballe-dev libdballe-doc libdballe9 libdballef-dev libdballef5 python3-wreport
...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-dballe : Depends: python3 (< 3.11) but 3.11.2-1+b1 is to be installed
                  Recommends: python3-numpy but it is not going to be installed
 python3-wreport : Depends: python3 (< 3.11) but 3.11.2-1+b1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

do you plan to revive support for Debian stable and update the README?
are you working on building for Ubuntu 24.04 LTS (Noble Numbat) due this month?

**Comment by edigiacomo** [comment]
> do you plan to revive support for Debian stable and update the README?
> are you working on building for Ubuntu 24.04 LTS (Noble Numbat) due this month?

The answer is no to both questions: internally, we only use RHEL-based distributions and we haven't any Debian or Ubuntu machine. We solely support Ubuntu 22.04 because it's the choice made by Cineca for their server, and we don't have the resources to maintain any additional distributions, but feel free to download the source code and create the Debian/Ubuntu packages that you need, it shouldn't be difficult to adapt them starting from the packages for Ubuntu Jammy.

Furthermore, we haven't heavily advertised the Ubuntu repository because our sole user is Cineca; that's why you won't find it in the README
