### ISSUE TITLE
dballe::core::Record.set("l1", "-") is interpreted as 0 instead of missing.

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/dballe#29]
https://github.com/ARPA-SIMC/dballe/blob/master/dballe/core/record-test.cc#L187-L189

```
core_record.get_set_level: value '1,0,-,-' is different than the expected '1,-,-,-'
  core/record-test.cc:189:actual(rec.get_level()) == Level(1)
```

**Comment by spanezz** [comment]
I've now implemented it so that if a record value is set to *a string*, and the variable identified by the key is however *an integer or decimal*, and the string is only a dash, it does instead an unset.

I'm not sure this has ever worked before like this in dballe, and I'm not sure what is the actual use case here, so at the moment this is a feature that I am not sure I am able or willing to maintain in the future.

Can you give me some more details?

**Comment by edigiacomo** [comment]
I can't remember whether this ever worked in dballe, but we talked about representing the missing value as a `-` in both directions (set/get). Maybe in some pre-github mail?

But I remember that `Record::set_from_string()` supported it (until f00c819db806f3722b1e381b3df7383efeeff8ed) and I asked you if it was possible to reintroduce it.

Maybe `Record::setf()` is the right method (instead of `set()`)?

For example, I showed you (more than 1 year ago) the Web API I was implementing. The template is 
```
PIND,P1,P2/LEVELTYPE1,L1,LEVELTYPE2,L2/VAR
```
e.g. an instantaneous temperature at 2m above the surface is:
```
254,0,0/103,2000,-,-,B12101
```

We are trying to use this syntax for `MQTT` topics too - and it think it would be lovely to have the same syntax in `dbadb` (query params) `dbamsg dump`, Web API, etc.

If you don't want to implement nor mantain the feature, it's ok, we can consider it a convention used at ARPA-SIMC.

**Comment by spanezz** [comment]
`setf()` would be, I think, the right place for it. Is it ok if I move the implementation from `set()` to `setf()`?

**Comment by edigiacomo** [comment]
Yes, thank you!

**Comment by spanezz** [comment]
Done!

**Comment by pat1** [comment]
a me pare non valga ancora per i livelli come da
https://github.com/r-map/rmap/issues/81

**Comment by pat1** [comment]
```
mosquitto_sub -v -t rmap/pat1/\#
rmap/pat1/1131844,4449446/rmap/-,-,-/-,-,-,-/B01213 {"v":"conn"}
rmap/pat1/1131844,4449446/rmap/254,0,0/0,1,-,-/B12101 {"v":30690,"t":"2016-01-28T11:22:53"}
rmap/pat1/1131844,4449446/rmap/254,0,0/0,1,-,-/B12101 {"v":30690,"t":"2016-01-28T11:22:58"}

 mqtt2bufr -t rmap/pat1/\# | dbamsg dump 
#0 BUFR message: 148 bytes, origin 200:0, category 0 255:255:0, bufr edition 4, tables 14:1, subsets 1, values: 18/18:
Subset 0:
001194 [SIM] Report mnemonic(CCITTIA5): rmap
004001 YEAR(YEAR): 2016
004002 MONTH(MONTH): 1
004003 DAY(DAY): 28
004004 HOUR(HOUR): 11
004005 MINUTE(MINUTE): 24
004006 SECOND(SECOND): 55
001011 SHIP OR MOBILE LAND STATION IDENTIFIER(CCITTIA5): pat1
005001 LATITUDE (HIGH ACCURACY)(DEGREE): 44.49446
006001 LONGITUDE (HIGH ACCURACY)(DEGREE): 11.31844
007192 [SIM] First level type(NUMERIC): 0
007193 [SIM] Level L1(NUMERIC): 0
007195 [SIM] Second level type(NUMERIC): 0
007194 [SIM] Level L2(NUMERIC): 0
004192 [SIM] Time range type(NUMERIC): 0
004193 [SIM] Time range P1(NUMERIC): 0
004194 [SIM] Time range P2(NUMERIC): 0
001213 AIRBASE AIR QUALITY OBSERVING STATION CODE(CCITTIA5): conn
#1 BUFR message: 144 bytes, origin 200:0, category 0 255:255:0, bufr edition 4, tables 14:1, subsets 1, values: 18/18:
Subset 0:
001194 [SIM] Report mnemonic(CCITTIA5): rmap
004001 YEAR(YEAR): 2016
004002 MONTH(MONTH): 1
004003 DAY(DAY): 28
004004 HOUR(HOUR): 11
004005 MINUTE(MINUTE): 24
004006 SECOND(SECOND): 53
001011 SHIP OR MOBILE LAND STATION IDENTIFIER(CCITTIA5): pat1
005001 LATITUDE (HIGH ACCURACY)(DEGREE): 44.49446
006001 LONGITUDE (HIGH ACCURACY)(DEGREE): 11.31844
007192 [SIM] First level type(NUMERIC): 0
007193 [SIM] Level L1(NUMERIC): 1
007195 [SIM] Second level type(NUMERIC): 0
007194 [SIM] Level L2(NUMERIC): 0
004192 [SIM] Time range type(NUMERIC): 254
004193 [SIM] Time range P1(NUMERIC): 0
004194 [SIM] Time range P2(NUMERIC): 0
012101 TEMPERATURE/DRY-BULB TEMPERATURE(K): 306.90
```

**Comment by pat1** [comment]
reopened r-map/rmap#81
