### ISSUE TITLE
Impossible to open stdin and stdout from Fortran bindings

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/dballe#3]
In devel branch, the labels `(stdin)` and `(stdout)` were removed but from Fortran bindings is not possible to read from stdin or write to stdout (see [idba_messages_open_input](https://github.com/ARPA-SIMC/dballe/blob/devel/fortran/dballeff.h#L175) and [idba_messages_open_output](https://github.com/ARPA-SIMC/dballe/blob/devel/fortran/dballeff.h#L181)).

**Comment by spanezz** [comment]
This will be replaced by passing an empty string to idba_messages_open_input to mean stdin, and an empty string to idba_messages_open_output to mean stdout.

**Comment by spanezz** [comment]
Mergiato in devel, ma non ho avuto modo di testarlo. Lascio il bug aperto, lo chiudi tu quando vedi se va?

**Comment by pat1** [comment]
riportato modifica in libsim
bisogna fare dei test
