### ISSUE TITLE
missed information on error importing wrong json data

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#31]
dbadb import -t json --wipe-first --dsn=sqlite:/dev/shm/tmp.sqlite  tmp.json
Invalid JSON value

cat tmp.json
 [{"ident": null, "network": "arpav", "lon": 1187637, "lat": 4649926, "date": "2016-01-01T01:00:00Z", "data": [{"vars": {"B01019": {"v": "3 Arabba" },"B07030": {"v": 1645.0},"B07031": {"v": 1645.0} } }, {"timerange": [1,0,3600],"vars": {"B13011": { "a": { }, "v": 0.0 } },"level": [ 1,null,null,null]} ] },
 {"ident": null, "network": "arpav", "lon": 1187637, "lat": 4649926, "date": "2016-01-01T02:00:00Z", "data": [{"vars": {"B01019": {"v": "3 Arabba" },"B07030": {"v": 1645.0},"B07031": {"v": 1645.0} } }, {"timerange": [1,0,3600],"vars": {"B13011": { "a": { }, "v": 0.0 } },"level": [ 1,null,null,null]} ] }]

dbadb import -t json --wipe-first --dsn=sqlite:/dev/shm/tmp.sqlite tmp.json
unexpected character

cat tmp.json
 {"ident": null, "network": "arpav", "lon": 1187637, "lat": 4649926, "date": "2016-01-01T01:00:00Z", "data": [{"vars": {"B01019": {"v": "3 Arabba" },"B07030": {"v": 1645.0},"B07031": {"v": 1645.0} } }, {"timerange": [1,0,3600],"vars": {"B13011": { "a": { }, "v": 0.0 } },"level": [ 1,null,null,null]} ] },
 {"ident": null, "network": "arpav", "lon": 1187637, "lat": 4649926, "date": "2016-01-01T02:00:00Z", "data": [{"vars": {"B01019": {"v": "3 Arabba" },"B07030": {"v": 1645.0},"B07031": {"v": 1645.0} } }, {"timerange": [1,0,3600],"vars": {"B13011": { "a": { }, "v": 0.0 } },"level": [ 1,null,null,null]} ] }

**Comment by edigiacomo** [comment]
The error message is now (in 5ea7e54):

```
Error while parsing JSON from tmp.json at char 0: Invalid JSON value
```

In the first case, because the dballe JSON schema requires an object (not an array).

```
Error while parsing JSON from tmp.json at char 303: unexpected character
```

In the second case, because the first line ends with a comma (invalid character).

If this message is good for you, please close the issue.

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
