### ISSUE TITLE
dbamsg dump --interpreted do not output datetime information

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#32]
dbamsg dump --interpreted 
#0[0] generic message with 1 contexts:
Level -,-,-,-  tr -,-,-  5 vars:
001011 SHIP OR MOBILE LAND STATION IDENTIFIER(CCITTIA5): dancast78
001194 [SIM] Report mnemonic(CCITTIA5): rmap
001213 AIRBASE AIR QUALITY OBSERVING STATION CODE(CCITTIA5): conn
005001 LATITUDE (HIGH ACCURACY)(DEGREE): 44.69950
006001 LONGITUDE (HIGH ACCURACY)(DEGREE): 10.64555

mqtt2bufr -t rmap/dancast78/\#|dbamsg dump
#0 BUFR message: 112 bytes, origin 200:0, category 0 255:255:0, bufr edition 4, tables 14:1, subsets 1, values: 11/11:
Subset 0:
001194 [SIM] Report mnemonic(CCITTIA5): rmap
004001 YEAR(YEAR): 2016
004002 MONTH(MONTH): 1
004003 DAY(DAY): 29
004004 HOUR(HOUR): 12
004005 MINUTE(MINUTE): 14
004006 SECOND(SECOND): 55
001011 SHIP OR MOBILE LAND STATION IDENTIFIER(CCITTIA5): dancast78
001213 AIRBASE AIR QUALITY OBSERVING STATION CODE(CCITTIA5): conn
005001 LATITUDE (HIGH ACCURACY)(DEGREE): 44.69950
006001 LONGITUDE (HIGH ACCURACY)(DEGREE): 10.64555

**Comment by spanezz** [comment]
Done in 34692b3ad78fca6e24bf845037ab6a1a765f0634.

Datetime information is not printed in the data unless the input message had attributes on them. However, it is not always printed in any case in the first line for each message, together with rep_memo, coordinates, and ident:
```
#0[0] synop message, rep_memo: , 50.78390,6.09500, ident: , dt: 2009-02-24T12:00:00, 19 contexts:
```
