### ISSUE TITLE
Performance di dbadb import

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#39]
Ho cambiato la struttura delle transazioni SQL in DB-All.e e ora le performance di `dbadb import` dovrebbero essere migliorate in maniera significativa; vi chiederei di farmi sapere se notate qualcosa, e se è migliorato, di quanto è migliorato.

Se è migliorato in maniera significativa, vorrei far si che tutto quello che sta tra una preparati e una fatto stia dentro a un'unica transazione. Questo avrebbe un paio di effetti di cui vale la pena discutere, ma direi di farlo solo dopo aver misurato quanto cambia dbadb.

**Comment by spanezz** [comment]
Ho implementato la cosa per l'API fortran in maniera opzionale. Normalmente il comportamento è sempre lo stesso, ma se si setta `DBA_FORTRAN_TRANSACTION`, tutto quello che c'è tra una `preparati` e una `fatto` avviene in un'unica transazione, a meno ché la preparati non sia solo in `"read"`:
```sh
export DBA_FORTRAN_TRANSACTION=1
```
Dovrebbe andare piú veloce, almeno su MySQL e PostgreSQL, e se non viene chiamata la `fatto`, per esempio se c'è stato un errore, tutto quello che è stato fatto dopo la `preparati` è come se non fosse mai successo, cosí non si lasciano cose a metà.

**Comment by spanezz** [comment]
In https://github.com/ARPA-SIMC/dballe/blob/master/doc/dballe_env.md ho documentato le variabili di ambiente usate da DB-All.e.

**Comment by pat1** [comment]
*********************
* test del 20170117 *
*********************

Verification features of cosmo-leps:
16 members; 
1 months; 
2 forecast ranges (6-18, 18-30); 
1740 stations (1612 for scores);
6 thresholds;
radicchio - fedora24;
dballe-7.22-1.x86_64;
verifica-4.0-105.fc24.x86_64;

export stringa=`echo --dsn='mysql://radicchio.metarpa/vecmwfreload?user=montani&password=2428'`
time ./pipe2dba -i /scratch/amontani/verifica_test/long_verification/FullDom/obs_tp_only_FullDom/2016_09101112_tp12h_fulldom.bufr -o 'mysql://radicchio.metarpa/vecmwfreload?user=montani&password=2428'

export stringa=`echo --dsn=postgresql://amontani:2428@localhost/vecmwfreload`
time ./pipe2dba -i /scratch/amontani/verifica_test/long_verification/FullDom/obs_tp_only_FullDom/2016_09101112_tp12h_fulldom.bufr -o postgresql://amontani:2428@radicchio/vecmwfreload




               mysql       mysql                               postgres      postgres
               unset       V7                                  unset         V7

dbadb import   4m29.161s   0m56.948s                           4m58.262s     1m54.071s
                                                                             1m52.856s


               mysql       mysql       mysql     mysql         postgres      postgres      postgres     postgres
               unset       V7          unset     V7            unset         V7            unset        V7
                                       TRANSACT  TRANSACT                                  TRANSACT     TRANSACT
pipe2dba       6m5.322s    8m39.331s                           .........     10m9.949s
                                       6m2.452s  5m18.046s     8m13.541s     8m59.549s	   6m39.736s   	6m6.758s
