### ISSUE TITLE
interpretation of bufr like test-soil1.bufr

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/dballe#41]
Would it be a hard work to implement full interpretation of a bufr message like [extra/bufr/test-soil1.bufr](https://github.com/ARPA-SIMC/dballe/blob/master/extra/bufr/test-soil1.bufr)? I mean interpret context B07061 as depth below land (leveltype 106 according to [fapi_ltypes.md](https://github.com/ARPA-SIMC/dballe/blob/master/doc/fapi_ltypes.md)) and place temperature at that level. Now interpretation is limited to station data:

```
$ dbamsg dump --interpreted ../../../extra/bufr/test-soil1.bufr
#0[0] synop message with 1 contexts:
Level -,-,-,-  tr -,-,-  6 vars:
001001 WMO BLOCK NUMBER(NUMERIC): 11
001002 WMO STATION NUMBER(NUMERIC): 406
002001 TYPE OF STATION(CODE TABLE): 0
005001 LATITUDE (HIGH ACCURACY)(DEGREE): 50.06972
006001 LONGITUDE (HIGH ACCURACY)(DEGREE): 12.39306
007030 HEIGHT OF STATION GROUND ABOVE MEAN SEA LEVEL (SEE NOTE 3)(M): 483.0
```

**Comment by spanezz** [comment]
Not a hard work once I already had the code in mind from #47

**Comment by dcesari** [comment]
Grande!
