### ISSUE TITLE
Nuovo formato database SQL "V7"

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#43]
Ho creato un nuovo formato di database sperimentale, implementato finora solo per sqlite e postgresql, che dovrebbe velocizzare un po' le cose almeno per PostgreSQL, perché cerca di fare tutto con meno query.

Di default dballe lavora sempre col formato stabile. Per provare quello nuovo esportare `DBA_DB_FORMAT=V7` prima di creare un nuovo database.

Il database V7 si comporta come memdb, per cui a un ana_id corrisponde un'unica combinazione di (lat, lon, ident e rep_memo) invece di (lat, lon, ident) come nel formato attuale.

Apro questo issue per tracciare le prove che si fanno.

**Comment by spanezz** [comment]
Ho appena finito (testato e push-ato in master) di aggiornare il formato V7 cambiando al gestione degli attributi secondo #44 e salvandoli nella stessa tabella dei dati, cosa che dovrebbe evitare molte query ai database in fase di importazione ed esportazione.

**Comment by spanezz** [comment]
Il database V7 è ora implementato per sqlite, postgresql e mysql.

**Comment by brancomat** [comment]
Chiudo il bug perché la cosa è implementata e mi pare che la questione ora sia relativa a benchmarkare le varie versioni di db e quindi in qualche modo inclusa nel #23
(eventualmente rimpallabile in caso di urgenze a nuovo bug tipo: "siamo pronti per usare V7 in produzione?" ma sarebbe sempre la stessa zuppa)

**Comment by brancomat** [comment]
Riapro il bug per richiesta di chiarimento:

> Di default dballe lavora sempre col formato stabile. Per provare quello nuovo esportare DBA_DB_FORMAT=V7 prima di creare un nuovo database.

questo vuol dire esportare la variabile _solo_ al momento del primo `dbadb wipe` o `dbadb import` (e poi il resto dei dballecomandi sono abbastanza smart da dedurre il formato del db esistente da soli), o per tutte le dballeinterazioni va mantenuta esportata la variabile?

**Comment by spanezz** [comment]
Solo al momento di `dbadb wipe` o `dbadb --wipe-first …`

Quando dballe lavora su un database che già esiste, trova il formato e lo gestisce ammodino.
