### ISSUE TITLE
Comportamento degli attributi alla modifica dei dati

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#44]
I dati possono essere importati (`dbadb import`) e inseriti (`prendilo`).

Ricordo che si era parlato di cosa dovrebbe succedere agli attributi già esistenti in quei due casi, ma non ricordo fosse mai stato definito niente.

Al momento il comportamento è:

* import: gli attributi importati si aggiungono agli attributi correnti, eventualmente sostituendo quelli che già esistono.
* prendilo: gli attributi esistenti vengono mantenuti immutati.

ricordo vagamente una richiesta di questo tipo:

* import: tutti gli attributi esistenti vengono rimossi, e gli unici attributi presenti dopo l'import sono quelli presenti nel messaggio importato.
* prendilo: tutti gli attributi esistenti vengono rimossi.

Prima di procedere a studiare strategie piú efficienti di gestione degli attributi, vorrei rendere definitiva questa specifica del loro comportamento.

**Comment by pat1** [comment]
riformulerei così:

*  import: tutti gli attributi riferiti a dati importati già esistenti vengono rimossi, e gli attributi presenti dopo l'import sono quelli presenti nel messaggio importato e quelli di altri dati preesistenti non riscritti
*  prendilo: tutti gli attributi esistenti dei dati riscritti vengono rimossi.

io e Davide

**Comment by spanezz** [comment]
Ok. Un dato si considera riscritto se è coinvolto in un import o una prendilo, anche se il valore nuovo è lo stesso del valore vecchio, giusto?

**Comment by dcesari** [comment]
On 29/03/2016 13:07, Enrico Zini wrote:
> Ok. Un dato si considera riscritto se è coinvolto in un import o una
> prendilo, anche se il valore nuovo è lo stesso del valore vecchio, giusto?

Scusa, il ritardo, sì possiamo assumere che è così, non ha senso 
distinguere i casi valore == o !=.

**Comment by spanezz** [comment]
Ok. Questo comportamento è ora implementato nel database formato V7 (v. #43).

**Comment by spanezz** [comment]
Implementerò questo comportamento anche nel formato MEM, mentre per il formato V6 non so se sia possibile.

**Comment by brancomat** [comment]
Il formato MEM implementa già il V7 per default dalla 7.16
