### ISSUE TITLE
fortran API: error: cannot insert attributes for variable 000000: no data id given or found from last prendilo()

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#45]
From libsim examples I get this trace:
```
 // ** Execution begins **
 auto_ptr<DB> db0(DB::connect_from_url("sqlite:/tmp/dballe.sqlite"));
 DbAPI dbapi0(*db0, "write", "write", "write");
 dbapi0.scopa();
 MsgAPI msgapi1("/dev/null", "w", BUFR);
 // msgapi1 not used anymore
 M sgAPI msgapi1("/dev/null", "w", BUFR);
 // msgapi1 not used anymore
 dbapi0.unsetall();
 dbapi0.seti("lat", 4500000);
 dbapi0.seti("lon", 1000000);
 dbapi0.unset("ident");
 dbapi0.unset("mobile");
 dbapi0.setc("rep_memo", "generic");
 dbapi0.setdate(2014, 1, 6, 18, 0, 0);
 dbapi0.setlevel(105, 2000, 2147483647, 2147483647);
 dbapi0.settimerange(4, 3600, 7200);
 dbapi0.seti("B13003", 85);
 dbapi0.prendilo();
 dbapi0.setd("*B33192", 30.000000);
 dbapi0.seti("*B33193", 50);
 dbapi0.setd("*B33194", 70.000000);
 dbapi0.critica();
 dbapi0.seti("B12101", 27315);
 dbapi0.prendilo();
 dbapi0.setd("*B33192", 30.000000);
 dbapi0.seti("*B33193", 50);
 dbapi0.critica();
 // error: cannot insert attributes for variable 000000: no data id given or found from last prendilo()
```

**Comment by spanezz** [comment]
At this point:

        dbapi0.seti("B12101", 27315);

the input record has two B values (B13003 and B12101), so the following prendilo inserts two values. the last critica therefore cannot know which variable the attributes are referring to, and complains.

In e6103108 I changed the error message to be more helpful: `the last prendilo inserted 2 variables, and *var_related is not set`.

The code can be fixed with an unsetb before setting `B12101`. Should prendilo be changed to do unsetb automatically after it has run?

**Comment by pat1** [comment]
This is a test that was OK in the past without terminate with error.
Now setting var_related solve the problem but so I have to setb and var_related every time.
I left to you to choise to write an automatic unsetb after a prendilo.

**Comment by spanezz** [comment]
In alternativa, puoi anche fare unsetb dopo la prendilo, cosí eviti anche di inserire due variabili alla prendilo successiva, quando l'intenzione è inserirne solo una.

La cosa che rappresenta meglio l'intenzione di quel codice mi sembra sia far fare una unsetb automaticamente dentro alla prendilo, dopo aver inserito le variabili date. Non è una scelta mia però: sei tu che mi dici quello che deve fare l'API, e cosa si può rompere se qualche comportamento cambia.

Procedo a fare l'unsetb automatico nella prendilo? Ti va bene?

**Comment by pat1** [comment]
direi di si, poi faccio un giro di test

**Comment by spanezz** [comment]
Ok, implementato. Ti assegno il bug per chiuderlo dopo il giro di test.
