### ISSUE TITLE
dbadb export  return "write to temporary file was interrupted"

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#54]
dbadb export --dsn=rmap lat=44.65305 lon=11.62301 month=04 year=2016 >richardson_aprile.bufr
write to temporary file was interrupted

**Comment by pat1** [comment]
Al momento questo impedisce l'estrazione dei dati di aprile della stazione "richardson" in campo a SPC.su un DSN alimentato in tempo reale. Il DSN dovrebbe essere a ripulitura periodica, ma la ripulitura non può essere eseguita senza aver salvato i dati di questa stazione che dovranno essere accuratamente analizzati all'interno del progetto per la misura del numero di richardson che fa capo a Ines Cerenzia. La non ripulitura porta a un graduale deterioramento delle performance del server e la possibile perdita dei dati in tempo reale.

**Comment by pat1** [comment]
Per il momento ho tamponato estraendo i dati per giorno invece che per mese.

**Comment by spanezz** [comment]
Come posso riprodurre questo problema? Funziona da qualsiasi macchina in rete ARPA?

**Comment by spanezz** [comment]
Mi sembra che il --dsn che c'è nell'esempio usi ancora ODBC, che è stato rimosso nell'ultima versione di dballe (#42)

**Comment by pat1** [comment]
dballe-7.8-1
il dsn è mysql
non è riproducibile in rete ARPA (macchina di ARPA Veneto)
il DSN è stato wipato e parte dei dati sono stati dumpati in bufr

Se non hai idea da dove il messaggio "write to temporary file was interrupted" possa venir fuori posso provare a ricostruire un db e una query abbastanza grande da riprodurre il problema.

**Comment by spanezz** [comment]
si, per favore: non ho idea da dove venga fuori quell'errore

**Comment by brancomat** [comment]
Gli odbc son stati abbandonati come da #42

**Comment by pat1** [comment]
[richardson_aprile.bufr.tgz.zip](https://github.com/ARPA-SIMC/dballe/files/252521/richardson_aprile.bufr.tgz.zip)
questa è una parte dei dati nel db, ma tutti quelli oggetto della query, per chi avesse voglia di riprovare in futuro

**Comment by spanezz** [comment]
Probabilmente questo problema non è legato a ODBC e non avrei problemi a tenere aperto il bug, però ancora non ci sono istruzioni che mi mettano in condizioni di riprodurlo.

**Comment by pat1** [comment]
Nonostante questo bug sia chiuso se Enrico ha intenzione e interesse di affrontarlo il problema si ripropone per maggio, ma non ho idea di quali procedure, approvazioni, bolli o controbolli siano necessari.
```
dbadb export --dsn=rmap lat=44.65305 lon=11.62301 month=05 year=2016  > richardson_maggio.bufr
write to temporary file was interrupted
```
la cosa, come mi pareva evidente, si replica con la url:
```
dbadb export --dsn="mysql:///rmap?user=utente&password=parolasegreta" lat=44.65305 lon=11.62301 month=05 year=2016  > richardson_maggio.bufr
write to temporary file was interrupted
```
La macchina dove si verifica non è di mia  gestione ma un modo per fare debug lo troviamo, ma la cosa se si fa deve essere fatta entro una decina di giorni in quanto il DB deve essere ripulito.

**Comment by dcesari** [comment]
Ma non sarà che ti si riempie banalmente /tmp o hai /tmp su tmpfs in memoria?

**Comment by pat1** [comment]
df -h
tmpfs           502M  8,0K    502M   1% /tmp

KiB Swap:  2129916 total,  1457068 used,   672848 free,   149048 cached

**Comment by spanezz** [comment]
Capisco la tua frustrazione, ma finché in questo bug non compare un elenco passo passo su come poter riprodurre la cosa, io posso solo ripetere fino alla noia quello che ho già scritto: "però ancora non ci sono istruzioni che mi mettano in condizioni di riprodurlo".

Esempio di istruzioni:
 1. fai ssh alla macchina xxx con credenziali che ti invio in privato)
 2. vai in questa directory
 3. esegui questo comando

Considera che la mia motivazione per dedicare tempo a questo problema è direttamente proporzionale a quanto questo problema è collegato con l'oggetto del mio contratto di lavoro in corso, e inversamente proporzionale a quante volte devo chiedere un elenco chiaro di passi che mi mettano in condizione di riprodurlo.

**Comment by pat1** [comment]
Bhe, fino a quando questo bug rimane chiuso il probema non si pone.
Se e quando verrà riaperto seguiranno le istruzioni se possibile.

**Comment by spanezz** [comment]
Finché non ci sono istruzioni per riprodurre il problema non vedo il motivo di riaprire il bug, quindi a questo punto rimarrà chiuso.

Se il problema si ripresenta in maniera riproducibile, apri pure un nuovo bug.

**Comment by pat1** [comment]
Scusa Enrico, ma la questione è interna a ARPAE. Il bug è stato chiuso da Daniele.
Se decidesse di riaprirlo allora potrai prendere il bug in considerazione e ci accorderemo sulle questioni tecniche per riprodurlo.
Io sto fornendo informazioni spero utili alla decisione se riaprirlo o no.
Quando e se riaperto dedicheremo tempo per riprodurlo.

**Comment by spanezz** [comment]
Io sinceramente spero che questo bug non verrà mai piú riaperto, perché il livello della discussione, che mi riguardi o no, è sceso abbastanza da farmi passare la voglia di guardarlo. Se i commenti aggressivi che sono stati postati qui hanno a che fare con questioni interne ad arpa e non con il problema tecnico in oggetto, per favore discutetele nei corridoi di arpa, non qui.

Credo che la cosa migliore da fare a questo punto sia "Lock conversation". Guarderò volentieri a un nuovo bug sullo stesso argomento che contenga solo informazioni tecniche e istruzioni per riprodurre il problema.

**Comment by pat1** [comment]
Il comando:
```
dbadb export --dsn="mysql:///rmap?user=utente&password=parolasegreta" lat=44.65305 lon=11.62301 month=05 year=2016  > richardson_maggio.bufr
```
scrive dei file del tipo:
```
/tmp/dballe-xxxxx
```
un giorno di dati estratti scrive 50Mbyte in /tmp
Avendo una /tmp di 500Mbyte risulta evidente che più di 10 giorni alla volta risulterà difficile riuscire ad estrarli.
Una export di TMPDIR a un filesystem abbastanza grande dovrebbe risolvere il problema.

**Comment by spanezz** [comment]
Ti chiedo per cortesia di rileggere [questo mio commento](https://github.com/ARPA-SIMC/dballe/issues/54#issuecomment-223956474), e di rispettare la mia richiesta.

Per cortesia apri un nuovo issue se vuoi che io mi occupi di questo problema.

**Comment by pat1** [comment]
Confermo che assegnare TMPDIR a un filesystem abbastanza grande risolve il problema.
Rimane il dubbio sulla necessità di disporre di circa 1,5G di spazio disco per estrarre 31M di bufr.
