### ISSUE TITLE
exporting data with rep_memo not in archive return error

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#55]
Hoto reproduce:
dbadb wipe --dsn=sqlite:/tmp/test.sqlite
[pat1@asus-pat1 ~]$ dbadb export rep_memo=mnw --dsn=sqlite:/tmp/test.sqlite
looking for repinfo corresponding to 'mnw'
[pat1@asus-pat1 ~]$ echo $?
1

In application like Borinud this stop elaboration when the expected is that no data should be returned.

**Comment by spanezz** [comment]
Done in 191af0a1e72dd162aab8fb81fd688750633c4f01
