### ISSUE TITLE
remove user and password from API

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#57]
following https://github.com/ARPA-SIMC/libsim/issues/15
I suggest to remove username and password from all APIs.
I can start to do this in libsim and when ready should be done in dballe too.

**Comment by spanezz** [comment]
So far I kept those two arguments only for compatibility with existing code, but they are ignored: I'll remove them very gladly.

An alternative to removing them from `idba_presentati` is to leave `idba_presentati` as it is, and then create a new function `idba_connect` that does exactly the same as `idba_presentati`, but only takes a `url` argument. That still provides a clear connect function, and has the advantage of not breaking the existing API, and not requiring a soname change (`libdballef4` to `libdballef5`).

**Comment by spanezz** [comment]
Is it ok if I add `idba_connect` and deprecate `idba_presentati` instead?

**Comment by spanezz** [comment]
Fatto come conseguenza di #61, visto che uscendo da CNF cambiamo il soname di libdballef
