### ISSUE TITLE
Duplicate variable

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/dballe#58]
In dballe .txt we have two entries for sea temperature, B22042 and B22043, with different precision and historically used in different templates. Since B22043 is the reference variable internally used by dballe when interpreting bufr, can we drop B22042 in dballe.txt to avoid confusion and leave it only in wreport tables?

Since I opened a branch for modifying dballe.txt I can add this modification to the branch together with others before making a PR.

I attach 2 ECMWF bufr files using variable B22042, if needed for testing.
[ship_bufr.zip](https://github.com/ARPA-SIMC/dballe/files/293568/ship_bufr.zip)

**Comment by dcesari** [comment]
More info: a test using a local `dballe.txt` **without** definition of B22042 did not show problems in dumping/interpreting/converting the bufr attached, which **does** have B22042.

**Comment by spanezz** [comment]
I'm ok merging that branch: the code seems to already be aware that that information can come in both as B22042 and as B22043, and uses B22043 internally.

**Comment by dcesari** [comment]
I made the pull request before your reply, so B22042 was not eliminated in dballe.txt, can you remove it in master directly, or...?

**Comment by spanezz** [comment]
Done. As a general idea, feel free to commit anything you want to master as long as `./run-check` doesn't complain.
