### ISSUE TITLE
Performance di memdb

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/dballe#59]
Ci siamo accorti che le performance di memdb in importazione, usato in libsim per importare file bufr, peggiorano fortemente e non linearmente all'aumentare della dimensione del file bufr, si arriva a 17 minuti per un file di ~1.5MB e ~7Kmessaggi. L'importazione su database "vero", es sqlite, non mostra il problema. Esempio per riprodurre:
```
wget ftp://ftp.smr.arpa.emr.it/incoming/dav/arpapiemonte/common20160229
for n in 10 50 100 500 1000 5000; do dbamsg cat --index=1-$n common20160229 > testbufr_$n; done
for file in testbufr_* ; do echo $file; time dbadb import --dsn=mem: $file; done
```
Un risultato simile in termini di prestazioni si ottiene importando con v7d_transform di libsim; un grezzo profiling al volo con `perf top` mostra:
```
Samples: 136K of event 'cycles', Event count (approx.): 57059249544
Overhead  Shared Object                       Symbol
  61,01%  libstdc++.so.6.0.19                 [.] std::_Rb_tree_increment
   7,93%  libdballe.so.7.0.3                  [.] dballe::stl::stlutils::Itersection<unsigned long>::sync_iters
   3,80%  libdballe.so.7.0.3                  [.] dballe::stl::stlutils::SequenceIters<std::_Rb_tree_const_iterator<unsigned long> >::next
   2,43%  libdballe.so.7.0.3                  [.] dballe::stl::stlutils::SequenceIters<std::_Rb_tree_const_iterator<unsigned long> >::valid
   0,99%  [vdso]                              [.] __vdso_gettimeofday
   0,90%  libdballe.so.7.0.3                  [.] dballe::stl::stlutils::SequenceIters<std::_Rb_tree_const_iterator<unsigned long> >::get
```
mentre `export DBA_PROFILE=Y` non aggiunge nulla. Stiamo facendo qualche errore procedurale, o la situazione è questa?

**Comment by spanezz** [comment]
Facciamo una prova: in f3306efe4f0bac23fbb78121072b978faef8f083 ho sostituito memdb con l'implementazione di sqlite (V7, cosí ha lo stesso comportamento) aperto su `:memory:`.

Questo dovrebbe scalare, e sembra essere comunque piú veloce di sqlite aperto su un ramdisk. Se ha performance accettabili o migliori sui casi d'uso effettivi, mi piacerebbe molto tenere questo e buttar via memdb.

Nota: in questa versione di prova non funziona il salvataggio di memdb su disco alla fine dell'elaborazione.

**Comment by dcesari** [comment]
dbadb in questo modo è un fulmine, 5 secondi al posto di 17 minuti! Vedo se riesco a fare un test con libsim senza ripacchettizzare.

**Comment by dcesari** [comment]
Provato al volo su `v7d_transform` con `LD_LIBRARY_PATH` e confermo le prestazioni nettamente migliorate a parità di risultato. Se non si intravedono potenziali problemi (occupazione di memoria? casi in cui potrebbe accadere l'opposto?) sono d'accordo di sostituire memdb con sqlite in memoria, Paolo che dici?

**Comment by spanezz** [comment]
Come occupazione di memoria non mi preoccupo, anzi. L'unica feature che al momento si perde è la persistenza del memdb, che mi fu chiesta tempo fa da Paolo e non so se è piú stata usata. Come dicevo prima, è una feature di cui mi piacerebbe fare a meno, gestendo quel caso con un file sqlite temporaneo e l'uso di `--wipe-first`. Siete d'accordo?

**Comment by dcesari** [comment]
@pat1 hai qualcosa da obiettare o la approviamo?

**Comment by dcesari** [comment]
In 7.15-1
