### ISSUE TITLE
Make DBA_FORTRAN_TRANSACTION default?

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/dballe#67]
Dovremmo provare in casi reali di girare con `export DBA_FORTRAN_TRANSACTION=1` come documentato in https://github.com/ARPA-SIMC/dballe/blob/master/doc/dballe_env.md e decidere se quella modalità è più efficiente ed esente da bug, così da farla diventare il default.

**Comment by pat1** [comment]
credo che dipenda da configurazioni del server DB cosa avviene agli altri processi che accedono al DB mentre la transazione è aperta ...
cosa dovrebbe succedere? attendere con transazioni in sequenziale o ?

**Comment by spanezz** [comment]
Per MySQL, il default è [repeatable read](https://dev.mysql.com/doc/refman/5.7/en/innodb-transaction-isolation-levels.html).

Per PostgreSQL, il default è [read committed](https://www.postgresql.org/docs/9.1/static/transaction-iso.html).

Per DB-All.e io non ho preferenze su quale comportamento sia desiderato, e direi che stia a voi decidere che garanzie volete avere. Con `DBA_FORTRAN_TRANSACTION` non settato, di garanzie legate alle transazioni tra la `preparati` e la `fatto` non ce ne sono, quindi la scelta sembra essere abbastanza libera.

**Comment by pat1** [comment]
Qualcuno ha fatto delle prove ?

**Comment by pat1** [comment]
Possiamo fare delle prove di performance della libsim con DBA_FORTRAN_TRANSACTION attivato ?
Per poi attivarlo come default.

**Comment by brancomat** [comment]
Questi gli ultimi test by @amontani : 

-----

>Ho effettuato una breve prova (vedi qui sotto le caratteristiche) sempre con postgresql con e senza `export DBA_FORTRAN_TRANSACTION=1`

```
-----------------------------
5 days;
3 forecast ranges;
....
------------------------------

                         con "export DBA..."        senza "export DBA... "
*** carica oss     5m39,57s                      5m37,10s
*** carica fcst     2m59,74s                      6m33,19s
*** scores           0m17,78s                     0m54,84s
```
> Quindi, l'utilizzo di `DBA_FORTRAN_TRANSACTION=1` sembra portare una notevole riduzione dei tempi nel caricamento dei previsti e negli scores (dove infatti vengono usati codici fortran).
> Questa sera, effettuo una prova lunga con `DBA_FORTRAN_TRANSACTION=1` per verificare la portata dell'impatto con tanti dati in gioco

----

**Comment by brancomat** [comment]
Riporto gli altri test di Andrea:

----
> l'impatto positivo di DBA_FORTRAN_TRANSACTION=1 è confermato anche x dataset più grossi.
```
postgresql-9.5.7-1.fc24.x86_64
dballe-7.27-1.x86_64
verifica-4.1-107.fc24.x86_64

*** carica oss                       5m37,33s
*** carica fcst                   3h20m29,23s
*** scores (mapdom)                 19m15,00s
*** scores (fulldom)                18m
                                     ----------
                                      4h05m
```

> Quindi, in totale, il "business" della verifica trimestrale dura adesso circa 4h, mentre prima si impiegavano 10h.
> I tempi di caricamento dei previsti e di scores sono più che dimezzati.
----

**Comment by pat1** [comment]
OK to Make DBA_FORTRAN_TRANSACTION default
