### ISSUE TITLE
dbaexport in gnuR format: possible bug?

### ISSUE THREAD

**Issue by umberto-pellegrini** [ARPA-SIMC/dballe#70]
Ho qualche perplessità sull'esportazione in formato gnuR tramite dbaexport.
Lo stesso sqlite esportato nei due formati csv e gnuR mostra risultati  differenti come contenuto, ed anche come dimensione, seppur questa seconda cosa non di certo probante (100kB rispetto a 3.4 MB di csv e di 4.4 MB di sqlite).

Il comando utilizzato è:
[2016-08-26.sqlite.zip](https://github.com/ARPA-SIMC/dballe/files/467686/2016-08-26.sqlite.zip)
[2016-08-26.csv.zip](https://github.com/ARPA-SIMC/dballe/files/467687/2016-08-26.csv.zip)
[2016-08-26.RData.zip](https://github.com/ARPA-SIMC/dballe/files/467685/2016-08-26.RData.zip)
dbaexport --dsn=sqlite:2016-08-26.sqlite --outfile :2016-08-26.csv csv
dbaexport --dsn=sqlite:2016-08-26.sqlite --outfile :2016-08-26.RData gnur

Il file gnuR, caricato in ambiente R con il comando load(), mostra un solo campo, il B12101, a cui sono riferiti molti numeri, tra cui data, anagrafica stazione ed un valore che immagino sia la temperatura. R interpreta questo oggetto come array numerico:
 num [1:871, 1:96, 1, 1, 1:15]
Me lo sarei aspettato come un dataframe.

Lo stesso file csv invece mostra un header ben più articolato, con anche gli attributi B33192,B33193,B33194 esportati.

**Comment by pat1** [comment]
Confermando le dimensioni maggiori del file csv (come ci si aspetta) nel nostro caso pare funzionare correttamente.
Nel workspace di R credo siano eliminati gli attributi (che infatti non sappiamo dove metterli).
Le matrici multidimensionali con nome "codice variabile" hanno come dimensione:
(ana,time,level,timerange,network)

A me pare che sia corretto anche nel tuo caso.

Sezionando la matrice si ottiene quello che si vuole.

**Comment by pat1** [comment]
ecco un  esempio
```
load("area56.Rdata")
str(B12101)
temperatura<-matrix(B12101[,,1,1,1])
# temperatura in tutte le stazioni per tutte le date primo livello timerange e rete

 h<-hist(temperatura,xlim=c(260,300),breaks=400)
 xfit<-seq(260,300,length=length(temperatura))
 yfit<-dnorm(xfit,mean=278.5,sd=3.8)
 yfit <- 0.22*yfit*diff(h$mids[1:2])*length(temperatura) 
 lines(xfit, yfit, col="blue", lwd=2)

 plot(density(temperatura,na.rm=T,bw=1,from=250,to=320))

 plot(density(temperatura,na.rm=T,bw=1),log="y")
```

**Comment by pat1** [comment]
@spanezz è vero che ci sono anche gli attributi e dove li trovo?

**Comment by spanezz** [comment]
On Tue, Oct 11, 2016 at 01:58:57AM -0700, Paolo Patruno wrote:

> @spanezz è vero che ci sono anche gli attributi e dove li trovo?

Se si esporta in R una variabile B12101 e un attributo B33007, in R
dovrebbero esserci una matrice "B12101" e una matrice "B12101.B33007".

C'è?


Enrico

-- 
GPG key: 4096R/634F4BD1E7AD5568 2009-05-08 Enrico Zini <enrico@enricozini.org>

**Comment by pat1** [comment]
non più replicabile
