### ISSUE TITLE
setting "varlist", to "B10004,B12101,B12103" and unset "*varlist" return unwanted data

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#73]
related with https://github.com/ARPA-SIMC/libsim/issues/27

this is a segmet of the trace that show the problem: 

dbapi0.unsetall();
dbapi0.unset("lat");
dbapi0.unset("lon");
dbapi0.unset("ident");
dbapi0.unset("mobile");
dbapi0.unset("rep_memo");
dbapi0.unset("var");
dbapi0.unset("limit");
dbapi0.unset("priority");
dbapi0.unset("priomin");
dbapi0.unset("priomax");
dbapi0.unset("latmin");
dbapi0.unset("lonmin");
dbapi0.unset("latmax");
dbapi0.unset("lonmax");
dbapi0.unset("ana_filter");
dbapi0.unset("data_filter");
dbapi0.unset("attr_filter");
dbapi0.unset("query");
dbapi0.unset("yearmin");
dbapi0.unset("monthmin");
dbapi0.unset("daymin");
dbapi0.unset("hourmin");
dbapi0.unset("minumin");
dbapi0.unset("secmin");
dbapi0.unset("yearmax");
dbapi0.unset("monthmax");
dbapi0.unset("daymax");
dbapi0.unset("hourmax");
dbapi0.unset("minumax");
dbapi0.unset("secmax");
dbapi0.setc("varlist", "B10004,B12101,B12103");
dbapi0.unset("*varlist");
ires = dbapi0.voglioquesto();
wassert(actual(ires) == 1314);
sres = dbapi0.dammelo();
wassert(actual(sres) == "B02003");
sres = dbapi0.dammelo();
wassert(actual(sres) == "B02011");
sres = dbapi0.dammelo();
wassert(actual(sres) == "B02013");
sres = dbapi0.dammelo();
wassert(actual(sres) == "B02014");
sres = dbapi0.dammelo();
wassert(actual(sres) == "B04086");
sres = dbapi0.dammelo();
wassert(actual(sres) == "B05015");
sres = dbapi0.dammelo();
wassert(actual(sres) == "B06015");
sres = dbapi0.dammelo();
wassert(actual(sres) == "B08042");
sres = dbapi0.dammelo();
wassert(actual(sres) == "B10004");
ires = dbapi0.voglioancora();
wassert(actual(ires) == 0);
sres = dbapi0.dammelo();
wassert(actual(sres) == "B10008");
sres = dbapi0.dammelo();
wassert(actual(sres) == "B11001");
sres = dbapi0.dammelo();
wassert(actual(sres) == "B11002");
sres = dbapi0.dammelo();
wassert(actual(sres) == "B12101");
ires = dbapi0.voglioancora();
wassert(actual(ires) == 0);
sres = dbapi0.dammelo();
wassert(actual(sres) == "B12103");
ires = dbapi0.voglioancora();
wassert(actual(ires) == 0);

**Comment by spanezz** [comment]
I'm trying to reproduce the bug. First finding: `unset("*varlist");` has no influence in this case, and the bug is just related to the handling of `varlist`.
