### ISSUE TITLE
Problem reimporting json

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/dballe#76]
Importing a json exported by dbamsg dump --json does not work, apparently for two different reasons:

```
dbamsg dump --json vprof.bufr > vprof.json
dbamsg dump -t json vprof.json
Value 17590 is outside the range [0,16382] for 010004 (PRESSURE)
```
while 17590 comes from

```
010004 PRESSURE(PA): 17590
```

which is an acceptable atmospheric pressure. Replacing `17590` by `17590.` and the same for all subsequent pressure values the error becomes:

```
dbamsg dump -t json vprof_modified.json
#1 message: 1 subsets: 1 generic: no low-level information available
```

[vprof.bufr.gz](https://github.com/ARPA-SIMC/dballe/files/655141/vprof.bufr.gz)
[vprof_modified.json.gz](https://github.com/ARPA-SIMC/dballe/files/655140/vprof_modified.json.gz)

**Comment by dcesari** [comment]
Maybe the second problem "no low-level information available" can be ignored because it does not apply to `dbadb` command, but `dbadb import -t json --wipe-first` also gives the first error on pressure as `dbamsg`.

**Comment by edigiacomo** [comment]
Which version of dballe are you using?

**Comment by dcesari** [comment]
dballe-7.21-1.x86_64

**Comment by edigiacomo** [comment]
Ok, I found the problem: when an integer is set on a variable with scale != 0, the value is considered as the value before applying the scale.

When scale < 0, the method `wreport::Var::format()` (invoked by the JSON serializer) format the value as an integer.  Therefore, the JSON reader cannot rely on the presence of a decimal or integer notation: every value must be treated as a string and set with `wreport::Var::setd()`.

**Comment by edigiacomo** [comment]
> dbamsg dump -t json vprof_modified.json
> #1 message: 1 subsets: 1 generic: no low-level information available

This problem is not fixed, I will open another issue.

**Comment by edigiacomo** [comment]
@dcesari the same thing happens with CSV format.
```
$ dbamsg dump vprof.bufr --csv --interpreted | dbamsg dump -t csv
#1 message: 1 subsets: 1 generic: no low-level information available
```
`dbamsg` need a "binary" (BUFR, AOF, CREX) representation of the input message. Feel free to open an issue if you want to convert JSON or CSV messages in other formats without using `dbadb`.
