### ISSUE TITLE
change order of data exported from dsn

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#83]
riferimento a  #82 #19 #81 

Forse mi sono dimenticato dell'utilizzo relativo alle stazioni mobili.
Seguendo l'attuale ordinamento un volo d'aereo (tenendo fissa l'ident quindi) risulta ordinato per coordinate, poi per il tempo ...
Seguire quindi l'evoluzione naturale di un parametro di una stazione mobile nel tempo e quindi nello spazio richiede un riordinamento;

E' possibile pensare un ordinamentio che soddisfi anche questo utilizzo (ident cambia lentamente; tempo cambia velocemente) ? Un tale cambiamento cosa potrebbe comportare?
*    lavoro di implementazione (molto/poco)
*    cambio delle performance ?
*    cambio degli applicativi ? (non credo)
*    altro ?

Se facciamo una veloce valutazione sarà poi possibile decidere se è preferibile implementare l'ordinamento negli applicativi che visualizzano stazioni mobili.

**Comment by spanezz** [comment]
Se ho capito bene ti serve un ordinamento diverso a seconda delle query che fai, e quindi un qualche tipo di API per chiedere l'ordinamento diverso. Qualcosa tipo `query=sort_by_datetime`?

Una volta decisa la API l'implementazione non dovrebbe essere molto lavoro, almeno se la limitiamo ai database V7.

Un eventuale cambio di performance non dovrebbe essere percettibile se non quando è attivato l'ordinamento per datetime. Non saprei direi come possa cambiare la performance quando è attivato l'ordinamento per datetime senza fare delle misure.

Cambiamenti degli applicativi non dovrebbero servirne, al netto di cambiamenti radicali alla API.

**Comment by edigiacomo** [comment]
Riassegnato a Paolo: probabilmente ieri, durante la revisione dei bug, l'interfaccia non ha preso il comando di riassegnazione.

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
