### ISSUE TITLE
howto export and delete data from a DSN?

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#84]
Is possible to export data from a DSN and delete it without lost data?

using dbadb export and dbadb delete is not transactional safe

Is possible to lock the DB in a manner that other application do not fail ?

the single dbadb export or dbadb delete are transactional safe?

**Comment by pat1** [comment]
Can I do it using python api ?

**Comment by spanezz** [comment]
You can by setting `DBA_FORTRAN_TRANSACTION=1` (see #67)

**Comment by pat1** [comment]
what are the equivalence in python for  idba_preparati and idba_fatto ?
I cannot find equivalence reading documentation.
For  idba_preparati probabile candidate is connect_from_url ...

```
DBA_FORTRAN_TRANSACTION
Wrap in a single database transaction everything that happens on a session between idba_preparati and idba_fatto, unless idba_preparati is called with only "read" access levels.

This should make execution faster at least on PostgreSQL and MySQL, and if idba_fatto is not called, like if the program aborts because of an error, then the partial work is rolled back rather than kept in the database.
```

**Comment by spanezz** [comment]
I do not understand your question: DB-All.e python bindings are not built on top of the fortran API.

What are you trying to do?

**Comment by pat1** [comment]
so what mean "You can by setting DBA_FORTRAN_TRANSACTION=1" for python API ?

**Comment by spanezz** [comment]
Ah sorry, I had misread "fortran API": you can do it with the fortran API by setting `DBA_FORTRAN_TRANSACTION=1`, I need to inspect the code to see how transactions are used in the Python API. Sould I do that?

**Comment by pat1** [comment]
we have to choose if:
* patch dbadb
* write a fortran tool
* write a python tool

* we have to do the task inside a python program so python is more natural than fortran.
* dbadb is a generic tool so is more natural than a specialized tool and with less dependencies

so take a look with python is a good think but at at very low priority; for now we do it with dbadb not safe.

**Comment by pat1** [comment]
ok per query=delete dentro una transazione.

**Comment by spanezz** [comment]
Now that it's possible to delete while iterating a result set in the python API (see #140), is that sufficient for what you need, or would `query=delete` still be needed?
