### ISSUE TITLE
document transaction in fortran and python API

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#86]
With an dballe upgrade daemon working with a permanent pipe like this:
```
mqtt2bufr -t rmap/\# -t mobile/\# |dbadb import -f --dsn="mysql:///mappo?user=xxx&password=yyy"
```
do not write in DB any more. The process run for a long time and/or terminate with a kill signal.

I think this is related to #84 with transaction active for import too.

**Comment by pat1** [comment]
The use of --fast 
```
dbadb import -f --fast
```
do not solve the problem; it introduce one more problem on other processes when try to add other data:
```
dbadb import -f --dsn="mysql:///mappo?user=xxx&password=yyy" otherdata.bufr

mysql Lock wait timeout exceeded; try restarting transaction
```

**Comment by spanezz** [comment]
`dbadb` issues a `COMMIT` after the input ends, so it fails with a continuous input. I can add options for controlling how commits are issued: what is the use case here?

**Comment by pat1** [comment]
The work around for now is to use a fortran program to do it.

The user case is :
  mqtt2bufr -t rmap/\# -t mobile/\# |dbadb import -f --dsn="mysql:///mappo?user=xxx&password=yyy"
mqtt2bufr is a program that subscribe to some mqtt topics from a broker and produce in stdout bufr; the program do not have to stop in normal case and every restart can produce data lost because mqtt broker do not have queue for messages; the bufr have to go in a mysql dballe db read by other applications.
I think that an other problem that can occur is the lost of connection to the mysql db if I do not receive messages for a long time ...
The use of xargs as is done in arkimet postprocessor is a possible approach ... a reconnect for each message I think is not a good solution.

**Comment by brancomat** [comment]
I might be wrong, but I think this is either a stackoverflow-like issue (on how to buffer a continuous input) or we have to internally rediscuss `dballe` specifications. The main readme still states:

> It is temporary, to be used for a limited time and then be deleted.

and imho this puts permanent pipes out of `dbadb` scope. Still, @spanezz insight on the issue could be precious but technically I don't see it as a dballe issue

**Comment by pat1** [comment]
Io penso che la questione riguardante dballe sia se in scrittura sia opportuno avere una unica modalità di scrittura che vede una intera sessione all'interno di una sola commit o non avere transazione del tutto rischiando inconsistenza del DB o prevedere anche una modalità che veda un commit per ogni messaggio; questa seconda modalità non è possibile nemmeno con le api fortran di dballe.
Viste le scarsissime performance di dballe da api fortran con le transazioni attivate (con grosse moli di dati in scrittura vedi report Montani di aprile) potrebbe essere una modalità da indagare.

Cosa c'entri questo con il readme di dballe non mi è chiaro.

Comunque il devel non è più bloccato in quanto come detto sopra l'applicazione fortran senza transazioni per ora funziona (rischiando incosistenze che si sono già verificate che si risolvono con un export/import vedi #85 ).
Ma visto che alcune questioni stanno emergendo nei primi utilizzi di dballe con accessi concorrenziali 
che dovranno presto andare operative (controllo di qualità) la conoscenza di come le transazioni sono state implementate mi pare importante (vedi #84)

Inoltre  opzioni quali  --fast (una volta utilizzate solo per sqlite?) non mi risultano assolutamente chiare come funzionino (vedi sopra).

Inoltre la funzionalità (da fortran) senza transazioni attive non mi pare funzionare come aspettato con sqlite e i dati non sono visibili fino alla fine del programma di scrittura, cosa che non avviene con mysql.

Se ritenete opportuno chiudo questa issue e voi ne aprite altre?

**Comment by pat1** [comment]
aggiungo importante riferimento a #67

**Comment by spanezz** [comment]
Ok, quindi si sta parlando di un'alimentazione continua di un database DB-All.e. Posso aggiungere un'opzione a dbadb che importa ogni singolo BUFR all'interno di una sua transazione, quindi c'è un commit per ogni messaggio in ingresso, e si importa o tutto il messaggio o niente (in caso di errore).

Questo va bene se l'alimentazione genera un rate limitato di messaggi: se si parla di un mesaggio ogni secondo o due, tipo, mi sembra la soluzione ideale. Se si parla di migliaia di messaggi al secondo, credo sia piú efficiente importarli in batch.

Cosa succede se viene generato un BUFR che dà errore con dbadb? Si chiude la pipe, e potenzialmente si perdono i messaggi successivi perché, come dici, il comando che genera i dati non accoda? Se questo può essere un problema, puoi ragionare di salvare invece i messaggi in arrivo in una cosa su disco, e importarli da quella coda, cosí un dbadb che fallisce non ti blocca la ricezione dei messaggi.

**Comment by pat1** [comment]
come dici tu anche secondo me questo caso concreto si risolve in modo ottimale sezionando la pipe in chunk ottimali da passare a singoli run di dbadb import che fanno una unica transazione. Suggerimenti su come fare i chunk sono ben accetti, ma assolutamente volontari.

In generale penso che espandere le api c++ fortran e python con la possibilità di fare commit intermedi senza richiedere una disconnessione e riconnessione possa essere utile in alcuni casi.
Questo permetterebbe di decidere su #67 rendendo la transazione sulla sessione il default (potendo gestire differentemente casi specifici con transazioni frammentate o disabilitate per accessi non concorrenziali).
Questo dovrebbe omogenizzare i comportamenti da dballe tools, libsim tools, e script python eliminando la possibilità di incosistenze su DB che ora mi sono risultate frequenti e poter gestire consistentemente export/delete da python o fortran come da  #84
Aggiungere opzioni a dbadb import non so se sia il caso se riusciamo a gestire la casistica con applicazioni specifiche ...
Se ritieni opportuno si può chiudere questa e aprire degli enhancement.

**Comment by spanezz** [comment]
Si, preferisco aprire degli enhancement, cosí tracciamo le varie casistiche specifiche
