### ISSUE TITLE
dbadb cleanup do not clear station that have no values

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#87]
dbadb stations  --url="mysql:///mappo?user=xxx&password=yyy" ident=pat1 lat=44.00000 lon 10.0000 
#0: -----------------------
000000 Station database ID(NUMERIC): 30
000000 Station is mobile(NUMERIC): 1
000000 Identifier of flight or ship(CCITTIA5): pat1
000000 Latitude(DEGREE): 44.00000
000000 Longitude(DEGREE): 10.00000
001011 SHIP OR MOBILE LAND STATION IDENTIFIER(CCITTIA5): pat1
001194 [SIM] Report mnemonic(CCITTIA5): rmap
001213 AIRBASE AIR QUALITY OBSERVING STATION CODE(CCITTIA5): disconn
005001 LATITUDE (HIGH ACCURACY)(DEGREE): 44.00000
006001 LONGITUDE (HIGH ACCURACY)(DEGREE): 10.00000

 dbadb export  --url="mysql:///mappo?user=xxx&password=yyy" ident=pat1 lat=44.00000 lon=10.0000 |wc
      0       0       0

 dbadb cleanup  --url="mysql:///mappo?user=xxx&password=yyy"

 dbadb stations  --url="mysql:///mappo?user=xxx&password=yyy" ident=pat1 lat=44.00000 lon 10.0000 
#0: -----------------------
000000 Station database ID(NUMERIC): 30
000000 Station is mobile(NUMERIC): 1
000000 Identifier of flight or ship(CCITTIA5): pat1
000000 Latitude(DEGREE): 44.00000
000000 Longitude(DEGREE): 10.00000
001011 SHIP OR MOBILE LAND STATION IDENTIFIER(CCITTIA5): pat1
001194 [SIM] Report mnemonic(CCITTIA5): rmap
001213 AIRBASE AIR QUALITY OBSERVING STATION CODE(CCITTIA5): disconn
005001 LATITUDE (HIGH ACCURACY)(DEGREE): 44.00000
006001 LONGITUDE (HIGH ACCURACY)(DEGREE): 10.00000

NB
the station is mobile

**Comment by pat1** [comment]
[rmap.dump.gz](https://github.com/ARPA-SIMC/dballe/files/704130/rmap.dump.gz)

**Comment by spanezz** [comment]
The station does not get cleared because it still has station data attached to it:
```
MariaDB [test]> select * from data where id_station=30;
+-----+------------+-----------+-----------+---------------------+--------+---------+
| id  | id_station | id_report | id_lev_tr | datetime            | id_var | value   |
+-----+------------+-----------+-----------+---------------------+--------+---------+
| 961 |         30 |       256 |        -1 | 1000-01-01 00:00:00 |    267 | pat1    |
| 962 |         30 |       256 |        -1 | 1000-01-01 00:00:00 |    450 | rmap    |
| 963 |         30 |       256 |        -1 | 1000-01-01 00:00:00 |    469 | disconn |
| 964 |         30 |       256 |        -1 | 1000-01-01 00:00:00 |   1281 | 4400000 |
| 965 |         30 |       256 |        -1 | 1000-01-01 00:00:00 |   1537 | 1000000 |
+-----+------------+-----------+-----------+---------------------+--------+---------+
5 rows in set (0.00 sec)
```

What behaviour would you expect from DB-All.e in a case like this?

**Comment by pat1** [comment]
from documentation:
 cleanup [options]
              Perform  database  cleanup  operations.  The only operation cur‐
              rently performed by this command is deleting stations that  have
              no  values.  

I understand, but I am wrong, that data are data and not constant station data.
I think that cleanup will be more useful if it delete  stations that  have no data with or without constant station data.
For example lat and lon, network and ident , if I am not wrong, are always present.

**Comment by spanezz** [comment]
Ok. There was a use case of storing in DB-All.e only constant station data, to use it to memorise an "anagrafica" of stations. In such a database, running `dbadb cleanup` will delete the entire database.
Is that what you would expect?

**Comment by pat1** [comment]
my user case is to have a db filled real time with only the last week of data, every day I delete  the oldest data; after some time the number of station go to increase without limit with station without data.
So the answer is "yes".

**Comment by spanezz** [comment]
Implemented, now a cleanup ignores the existance of constant station data when deciding whether to garbage collect a station with no data. Reassigning it to you for review.

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
