### ISSUE TITLE
arki-query autenticata

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/dballe#88]
Sarebbe utile avere la possibilità di usare arki-query con un server https autenticato es. con apache mod_proxy davanti all'arki-server, quindi:
1. passare al server le informazioni di autenticazione, es. leggendole da `.netrc`
2. gestire gli url https://
3. ehm...(problema strettamente personale) poter gestire un server https con certificato autofirmato, opzione -k di curl

**Comment by pat1** [comment]
qui siamo in dballe, forse dovresti metterla in arkimet?

**Comment by dcesari** [comment]
Spostata in arkimet:
https://github.com/ARPA-SIMC/arkimet/issues/72
