### ISSUE TITLE
rewrite attribures do not work on DB V6

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#94]
with those test bufr [bufr.zip](https://github.com/ARPA-SIMC/dballe/files/1091631/bufr.zip)

```
DBA_DB_FORMAT=V7 dbadb import --wipe-first --dsn=sqlite:test.sqlite3 issue91-withoutB33196.bufr 
DBA_DB_FORMAT=V7 dbadb import -f --dsn=sqlite:test.sqlite3 issue91-withB33196.bufr
````
this is OK
but with V6 :
```
dbadb import --wipe-first --dsn=sqlite:test2.sqlite3 issue91-withoutB33196.bufr
dbadb import -f --dsn=sqlite:test2.sqlite3 issue91-withB33196.bufr
````
produce:

```
dbadb export --dsn=sqlite:test2.sqlite3 |dbamsg dump --interpreted |grep 033196
         033196 [SIM] Data has been invalidated(CODE TABLE): 1
```
The attributes are missed

connected with #91 and https://github.com/ARPA-SIMC/dballe/pull/92

**Comment by edigiacomo** [comment]
Issue #44 is related. If the fix in V6 is not possible (see https://github.com/ARPA-SIMC/dballe/issues/44#issuecomment-210370627), we could close this issue but I think it's cleaner that V7 become the default version.

**Comment by spanezz** [comment]
I confirm that to implement this in V6 it would mean running a `DELETE * FROM attrs WHERE data_id=?` query every time a value is written, either by import or by `prendilo`.
I can implement it if you want, but I anticipate it will slow V6 data writes considerably. It would be easier to just switch to format V7 if you need this feature.

**Comment by edigiacomo** [comment]
No, thanks, I'd rather switching to v7 :)
